"""Hazmat / chemical / biological / radiological agent reference — CE-12 (v7.63).

Consumed by the Gaussian plume estimator in ``web/blueprints/specialized_threats.py``
and by CBRN reference UIs. Purely read-only reference data — no DB table yet.

Structure (per agent):

    id                  — short ID used in URLs
    name                — display name
    category            — 'chemical' | 'biological' | 'radiological' | 'nerve_agent' | 'blister_agent'
    cas_number          — Chemical Abstracts Service number (if applicable)
    un_number           — UN dangerous-goods number (if applicable)
    hazards             — list of primary hazards
    physical_state      — 'gas' | 'liquid' | 'solid' | 'aerosol'
    odor                — human-detectable odor (if any) at what concentration
    density_vs_air      — >1 sinks, <1 rises, ~1 neutral
    idlh_ppm            — Immediately Dangerous to Life or Health (NIOSH, ppm)
    erpg_1/2/3          — AIHA Emergency Response Planning Guidelines (ppm; 1hr)
                          ERPG-1: discomfort, ERPG-2: impaired action,
                          ERPG-3: life-threatening
    symptoms            — acute exposure signs (triage cue)
    route               — primary exposure route (inhalation / dermal / ingestion)
    decon               — decontamination protocol
    first_aid           — immediate treatment
    antidote            — specific antidote if available
    ppe_level           — OSHA Level A/B/C/D or N95/P100 for lower-risk
    evac_distance_m     — initial isolation + protective action distance (ERG 2024)
    notes               — operator notes / sources
    sources             — reference list

Sources: NIOSH Pocket Guide, DOT Emergency Response Guidebook (ERG) 2024,
AIHA ERPG values, CDC NIOSH IDLH database, WHO Biosafety Manual, FDA/CDC
select-agent datasheets, USAMRIID Blue Book on Biological Casualties.
"""

from __future__ import annotations

# Helper keeps each row scannable.
def _a(**kw):
    out = {
        'id': kw['id'],
        'name': kw['name'],
        'category': kw['category'],
        'cas_number': kw.get('cas_number', ''),
        'un_number': kw.get('un_number', ''),
        'hazards': kw.get('hazards', []),
        'physical_state': kw.get('physical_state', ''),
        'odor': kw.get('odor', ''),
        'density_vs_air': kw.get('density_vs_air', 1.0),
        'idlh_ppm': kw.get('idlh_ppm'),
        'erpg_1': kw.get('erpg_1'),
        'erpg_2': kw.get('erpg_2'),
        'erpg_3': kw.get('erpg_3'),
        'symptoms': kw.get('symptoms', ''),
        'route': kw.get('route', 'inhalation'),
        'decon': kw.get('decon', ''),
        'first_aid': kw.get('first_aid', ''),
        'antidote': kw.get('antidote', ''),
        'ppe_level': kw.get('ppe_level', ''),
        'evac_distance_m': kw.get('evac_distance_m', 0),
        'notes': kw.get('notes', ''),
        'sources': kw.get('sources', []),
    }
    return out


HAZMAT_AGENTS = [
    # ─── Industrial chemicals (TIC — Toxic Industrial Chemicals) ───
    _a(id='chlorine', name='Chlorine', category='chemical',
       cas_number='7782-50-5', un_number='1017',
       hazards=['toxic inhalation', 'corrosive', 'oxidizer'],
       physical_state='gas', odor='bleach-like, detectable at 0.3 ppm',
       density_vs_air=2.5,
       idlh_ppm=10, erpg_1=1, erpg_2=3, erpg_3=20,
       symptoms='Eye/throat burn, cough, chest tightness, pulmonary edema at high dose (delayed 2-24 hr)',
       route='inhalation',
       decon='Fresh air; flush eyes/skin with copious water ≥ 15 min',
       first_aid='Remove from source; 100% O2; bronchodilator for bronchospasm',
       antidote='None — supportive care',
       ppe_level='Level A (entry) / Level C (downwind)',
       evac_distance_m=800,
       notes='Heavier than air — accumulates in low-lying areas. WW1 weaponized.',
       sources=['ERG 2024 Guide 124', 'NIOSH IDLH 10 ppm']),

    _a(id='anhydrous_ammonia', name='Anhydrous Ammonia', category='chemical',
       cas_number='7664-41-7', un_number='1005',
       hazards=['toxic', 'corrosive', 'flammable'],
       physical_state='gas (liquefied under pressure)',
       odor='sharp/pungent, detectable at 5 ppm',
       density_vs_air=0.6,
       idlh_ppm=300, erpg_1=25, erpg_2=150, erpg_3=750,
       symptoms='Lacrimation, laryngospasm, frostbite on skin contact, chemical burns',
       route='inhalation',
       decon='Flush eyes/skin 15+ min; remove contaminated clothing',
       first_aid='100% humidified O2; bronchodilator; do NOT induce vomiting if ingested',
       antidote='None — supportive',
       ppe_level='Level A',
       evac_distance_m=150,
       notes='Farm + refrigeration hazard. Lighter than air but fog often hugs ground.',
       sources=['ERG 2024 Guide 125']),

    _a(id='hydrogen_cyanide', name='Hydrogen Cyanide (HCN)', category='chemical',
       cas_number='74-90-8', un_number='1051',
       hazards=['highly toxic', 'flammable'],
       physical_state='gas / liquid below 26 °C',
       odor='bitter almond — 20-60% of people CANNOT smell it (genetic)',
       density_vs_air=0.94,
       idlh_ppm=50, erpg_1=None, erpg_2=10, erpg_3=25,
       symptoms='Rapid onset: headache → confusion → seizure → death in minutes',
       route='inhalation/dermal',
       decon='Full strip + shower; cyanide adsorbs to skin',
       first_aid='100% O2; amyl nitrite inhalation pearl if available',
       antidote='Hydroxocobalamin 5 g IV (Cyanokit); OR sodium nitrite + thiosulfate',
       ppe_level='Level A',
       evac_distance_m=500,
       notes='Also produced in residential fires (polyurethane foam, wool). Zyklon-B.',
       sources=['ERG 2024 Guide 117', 'AAPCC cyanide guideline']),

    _a(id='phosgene', name='Phosgene (COCl2)', category='chemical',
       cas_number='75-44-5', un_number='1076',
       hazards=['highly toxic'],
       physical_state='gas',
       odor='freshly-cut hay — deceptively mild',
       density_vs_air=3.4,
       idlh_ppm=2, erpg_1=None, erpg_2=0.2, erpg_3=1,
       symptoms='Initial irritation → asymptomatic lucid interval (2-24 hr) → pulmonary edema',
       route='inhalation',
       decon='Fresh air; eye/skin irrigation',
       first_aid='Strict bed rest 48 hr; 100% O2; any exertion can precipitate fatal edema',
       antidote='None — supportive; N-acetylcysteine investigational',
       ppe_level='Level A',
       evac_distance_m=600,
       notes='WW1 weapon. Still produced industrially (pesticides, pharma).',
       sources=['ERG 2024 Guide 125', 'CDC phosgene datasheet']),

    _a(id='hydrogen_sulfide', name='Hydrogen Sulfide (H2S)', category='chemical',
       cas_number='7783-06-4', un_number='1053',
       hazards=['highly toxic', 'flammable'],
       physical_state='gas',
       odor='rotten eggs at low ppm — OLFACTORY FATIGUE at 100+ ppm (you stop smelling it)',
       density_vs_air=1.19,
       idlh_ppm=100, erpg_1=0.1, erpg_2=30, erpg_3=100,
       symptoms='Knockdown at 500+ ppm — one-breath death. Lower doses: headache, nausea.',
       route='inhalation',
       decon='Fresh air; no dermal decon normally needed',
       first_aid='Rescuers MUST have SCBA. 100% O2; nitrite therapy per cyanide protocol',
       antidote='Sodium nitrite 300 mg IV (forms methemoglobin that binds sulfide)',
       ppe_level='Level A (SCBA mandatory)',
       evac_distance_m=200,
       notes='Sewer, oil/gas, manure-pit, fish-processing hazard. Many 2-for-1 fatalities.',
       sources=['ERG 2024 Guide 117', 'OSHA H2S guide']),

    _a(id='chlorine_dioxide', name='Chlorine Dioxide (ClO2)', category='chemical',
       cas_number='10049-04-4', un_number='9191',
       hazards=['toxic', 'strong oxidizer', 'explosive at >10% in air'],
       physical_state='gas',
       odor='chlorine-like, irritating at 0.1 ppm',
       density_vs_air=2.3,
       idlh_ppm=5, erpg_1=0.1, erpg_2=0.5, erpg_3=3,
       symptoms='Eye/airway irritation, pulmonary edema',
       route='inhalation',
       decon='Fresh air; copious water',
       first_aid='100% O2',
       antidote='None',
       ppe_level='Level A',
       evac_distance_m=200,
       notes='Used in water treatment and paper bleaching. Many municipal-system releases.',
       sources=['NIOSH ClO2 datasheet']),

    _a(id='sulfur_dioxide', name='Sulfur Dioxide (SO2)', category='chemical',
       cas_number='7446-09-5', un_number='1079',
       hazards=['toxic', 'corrosive'],
       physical_state='gas',
       odor='sharp/suffocating at 1 ppm',
       density_vs_air=2.26,
       idlh_ppm=100, erpg_1=0.3, erpg_2=3, erpg_3=15,
       symptoms='Bronchoconstriction (especially asthmatics), mucous membrane burns',
       route='inhalation',
       decon='Fresh air; irrigate eyes',
       first_aid='100% humidified O2; bronchodilator',
       antidote='None',
       ppe_level='Level B',
       evac_distance_m=300,
       notes='Smelter, paper mill, volcanic emissions. Dense — accumulates in valleys.',
       sources=['ERG 2024 Guide 125']),

    _a(id='hydrogen_fluoride', name='Hydrogen Fluoride (HF)', category='chemical',
       cas_number='7664-39-3', un_number='1052',
       hazards=['highly toxic', 'corrosive — penetrates skin to bone'],
       physical_state='gas / liquid below 19.5 °C',
       odor='sharp/sour at 0.04 ppm',
       density_vs_air=0.69,
       idlh_ppm=30, erpg_1=2, erpg_2=20, erpg_3=50,
       symptoms='Delayed deep-tissue burns — pain increases over hours. Hypocalcemia/hyperkalemia.',
       route='inhalation + dermal',
       decon='Flood with water ≥ 30 min; apply calcium gluconate gel',
       first_aid='Calcium gluconate gel topical; SC/IV/IA calcium gluconate for extensive burns',
       antidote='Calcium gluconate 2.5% topical; 10% IV for systemic toxicity',
       ppe_level='Level A',
       evac_distance_m=100,
       notes='Refinery alkylation unit + etching hazard. Any HF burn > penny size → emergent.',
       sources=['ERG 2024 Guide 125', 'UpToDate HF exposure']),

    _a(id='methyl_isocyanate', name='Methyl Isocyanate (MIC)', category='chemical',
       cas_number='624-83-9', un_number='2480',
       hazards=['highly toxic', 'flammable', 'reactive with water'],
       physical_state='liquid / vapor at room temp',
       odor='sharp/pungent',
       density_vs_air=1.97,
       idlh_ppm=3, erpg_1=0.025, erpg_2=0.5, erpg_3=5,
       symptoms='Severe eye, upper airway and lung injury; delayed pulmonary fibrosis',
       route='inhalation',
       decon='Remove clothing; water flush — MIC reacts with water exothermically, use copious volume',
       first_aid='100% humidified O2; bronchodilator; atropine for glandular symptoms',
       antidote='None specific',
       ppe_level='Level A',
       evac_distance_m=600,
       notes='Bhopal 1984 release — worst industrial disaster in history.',
       sources=['CDC/ATSDR MIC']),

    _a(id='carbon_monoxide', name='Carbon Monoxide (CO)', category='chemical',
       cas_number='630-08-0', un_number='1016',
       hazards=['asphyxiant', 'flammable'],
       physical_state='gas',
       odor='odorless — THE silent killer',
       density_vs_air=0.97,
       idlh_ppm=1200, erpg_1=200, erpg_2=350, erpg_3=500,
       symptoms='Headache → confusion → loss of consciousness. Cherry-red skin is LATE.',
       route='inhalation',
       decon='Fresh air',
       first_aid='100% O2 via NRB; consider hyperbaric for COHb > 25% or pregnant/neuro symptoms',
       antidote='O2 (half-life 320 min room air; 80 min NRB O2; 23 min HBO)',
       ppe_level='SCBA',
       evac_distance_m=50,
       notes='Generators, improperly vented appliances, house fires. Pulse co-oximetry or arterial COHb.',
       sources=['AAPCC CO guideline', 'UHMS HBO indications']),

    # ─── Nerve agents (G-series / V-series) ───
    _a(id='sarin', name='Sarin (GB)', category='nerve_agent',
       cas_number='107-44-8', un_number='2810',
       hazards=['highly toxic — AChE inhibitor'],
       physical_state='liquid — volatile',
       odor='nearly odorless (fruity trace)',
       density_vs_air=4.86,
       idlh_ppm=0.03,
       erpg_1=None, erpg_2=0.0001, erpg_3=0.001,
       symptoms='SLUDGE (Salivation, Lacrimation, Urination, Defecation, GI, Emesis) + miosis + seizures',
       route='inhalation/dermal',
       decon='Remove clothing (90% of agent); bleach 0.5% or soap + water',
       first_aid='Atropine 2 mg IM repeat q5min until secretions dry; pralidoxime 600 mg IM x3; diazepam 10 mg IM for seizures',
       antidote='Atropine + 2-PAM Cl (DuoDote autoinjector)',
       ppe_level='Level A (MOPP 4)',
       evac_distance_m=800,
       notes='Tokyo subway 1995; Syria civil war. Vapor hazard worse indoors — ventilate.',
       sources=['USAMRIID Blue Book', 'DoD Medical NBC CPG']),

    _a(id='vx', name='VX', category='nerve_agent',
       cas_number='50782-69-9', un_number='2810',
       hazards=['highly toxic — persistent AChE inhibitor'],
       physical_state='oily liquid — low volatility, persistent',
       odor='nearly odorless',
       density_vs_air=9.2,
       idlh_ppm=0.003,
       erpg_1=None, erpg_2=0.00001, erpg_3=0.0001,
       symptoms='Same as sarin but primarily dermal — hours to onset; more persistent lethality',
       route='dermal/inhalation',
       decon='Strip + bleach 0.5% (hypochlorite hydrolyzes VX) then soap+water',
       first_aid='DuoDote x3 in legs; repeat atropine until secretions dry; diazepam for seizures',
       antidote='Atropine + 2-PAM Cl; multiple doses over hours',
       ppe_level='Level A (MOPP 4)',
       evac_distance_m=200,
       notes='100× more persistent than sarin. Assassination of Kim Jong-Nam 2017.',
       sources=['USAMRIID Blue Book']),

    _a(id='novichok', name='Novichok A-234', category='nerve_agent',
       cas_number='', un_number='',
       hazards=['highly toxic — 4th-generation AChE inhibitor'],
       physical_state='liquid / aerosol',
       odor='unknown',
       density_vs_air=7.5,
       idlh_ppm=None,
       erpg_1=None, erpg_2=None, erpg_3=None,
       symptoms='Same as sarin/VX; AChE inhibition may be RESISTANT to standard oxime (2-PAM) therapy',
       route='dermal/inhalation',
       decon='Strip + bleach + soap/water; prolonged skin contamination possible',
       first_aid='Aggressive atropine; consider HI-6 or obidoxime (not FDA-approved in US); supportive',
       antidote='Atropine + oxime (2-PAM may be ineffective)',
       ppe_level='Level A',
       evac_distance_m=500,
       notes='Salisbury UK 2018 (Skripal) + Navalny 2020. Resists standard decon.',
       sources=['OPCW Novichok advisory']),

    # ─── Blister agents ───
    _a(id='sulfur_mustard', name='Sulfur Mustard (HD)', category='blister_agent',
       cas_number='505-60-2', un_number='2810',
       hazards=['vesicant', 'carcinogen'],
       physical_state='oily liquid',
       odor='garlic / horseradish at high conc',
       density_vs_air=5.4,
       idlh_ppm=0.1,
       erpg_1=None, erpg_2=0.003, erpg_3=0.01,
       symptoms='Delayed 2-24 hr: eye/skin/airway blisters. No pain until lesions develop.',
       route='dermal/inhalation/ocular',
       decon='Strip + 0.5% hypochlorite + copious water. Decon within MINUTES — irreversible once absorbed.',
       first_aid='Symptomatic only: analgesia, wound care, airway support. Eye: lubricants, no patches.',
       antidote='None specific',
       ppe_level='Level A',
       evac_distance_m=200,
       notes='WW1 signature weapon. Decon window is < 2 min for meaningful efficacy.',
       sources=['USAMRIID Blue Book']),

    _a(id='lewisite', name='Lewisite (L)', category='blister_agent',
       cas_number='541-25-3', un_number='2810',
       hazards=['vesicant — contains arsenic'],
       physical_state='oily liquid',
       odor='geraniums',
       density_vs_air=7.2,
       idlh_ppm=None,
       erpg_1=None, erpg_2=0.003, erpg_3=0.01,
       symptoms='Immediate pain + blistering (unlike mustard). Systemic: shock, pulmonary edema.',
       route='dermal/inhalation',
       decon='Strip + hypochlorite + water',
       first_aid='BAL (British Anti-Lewisite / dimercaprol) 3 mg/kg IM q4h',
       antidote='Dimercaprol (BAL)',
       ppe_level='Level A',
       evac_distance_m=150,
       notes='WW1-era. Arsenic-based. Immediate onset distinguishes from mustard.',
       sources=['USAMRIID Blue Book']),

    # ─── Choking / pulmonary agents ───
    _a(id='chloropicrin', name='Chloropicrin (PS)', category='chemical',
       cas_number='76-06-2', un_number='1580',
       hazards=['toxic', 'lacrimator', 'pulmonary agent'],
       physical_state='liquid — volatilizes',
       odor='slightly sweet, intensely irritating',
       density_vs_air=5.7,
       idlh_ppm=2, erpg_1=0.1, erpg_2=0.3, erpg_3=1.5,
       symptoms='Lacrimation, bronchospasm, delayed pulmonary edema',
       route='inhalation',
       decon='Fresh air; flush exposed surfaces',
       first_aid='100% O2; bronchodilator; strict rest 48 hr',
       antidote='None — supportive',
       ppe_level='Level A',
       evac_distance_m=200,
       notes='Agricultural fumigant. Dense — settles in low areas.',
       sources=['NIOSH chloropicrin datasheet']),

    # ─── Biological agents ───
    _a(id='anthrax', name='Anthrax (Bacillus anthracis)', category='biological',
       cas_number='', un_number='',
       hazards=['Tier 1 select agent', 'pulmonary / cutaneous / GI forms'],
       physical_state='aerosol (spores)',
       odor='none',
       idlh_ppm=None,
       symptoms='Inhalation: 1-6 day flu-like prodrome → mediastinal widening, shock (>85% fatal untreated). Cutaneous: painless black eschar. GI: bloody diarrhea, shock.',
       route='inhalation / dermal / ingestion',
       decon='Soap + water; 0.5% hypochlorite for gross contamination. Spores are environmentally durable.',
       first_aid='Isolate (standard precautions; not person-to-person). Immediate antibiotics per suspected exposure.',
       antidote='Ciprofloxacin OR doxycycline PO/IV × 60 days + raxibacumab / anthrax immune globulin in severe cases',
       ppe_level='N95/P100 + gown/gloves (not person-to-person but spores)',
       evac_distance_m=0,
       notes='Not contagious person-to-person. Post-exposure prophylaxis within 48 hr is key. Vaccine (AVA) available for at-risk personnel.',
       sources=['CDC anthrax clinical guidance', 'USAMRIID Blue Book', 'WHO Anthrax in Humans and Animals 4th ed.']),

    _a(id='smallpox', name='Smallpox (Variola major)', category='biological',
       cas_number='', un_number='',
       hazards=['Tier 1 select agent', 'highly contagious'],
       physical_state='aerosol / droplet',
       odor='none',
       idlh_ppm=None,
       symptoms='7-17 day incubation → high fever + prostration → centrifugal rash (face + extremities > trunk), synchronous lesion progression. ~30% CFR in unvaccinated.',
       route='inhalation / droplet / fomite',
       decon='N/A (person-to-person). Soap + water for surface contact. Airborne isolation.',
       first_aid='Strict airborne + contact isolation. Notify public health IMMEDIATELY (global health emergency).',
       antidote='Tecovirimat (TPOXX) supportive; brincidofovir. Vaccinia vaccine within 4 days post-exposure.',
       ppe_level='N95 + eye protection + gown (airborne precautions)',
       evac_distance_m=0,
       notes='Eradicated 1980 — reintroduction would be a bioterror event. Person-to-person spread is the critical hazard. Single suspected case = public-health emergency.',
       sources=['CDC smallpox preparedness guidance', 'USAMRIID Blue Book', 'WHO smallpox eradication program records']),

    _a(id='plague', name='Plague (Yersinia pestis)', category='biological',
       cas_number='', un_number='',
       hazards=['Tier 1 select agent', 'pneumonic form is contagious'],
       physical_state='aerosol / flea vector',
       odor='none',
       idlh_ppm=None,
       symptoms='Bubonic: painful lymphadenopathy + fever. Pneumonic: 1-3 day incubation → fulminant pneumonia + hemoptysis (near 100% fatal untreated).',
       route='inhalation (pneumonic) / flea bite (bubonic)',
       decon='Soap + water. Droplet isolation for pneumonic.',
       first_aid='Droplet isolation. Immediate IV antibiotics for suspected pneumonic.',
       antidote='Streptomycin / gentamicin IV; doxycycline or cipro alternative. PEP: doxycycline or cipro × 7 days.',
       ppe_level='N95 + eye protection + gown',
       evac_distance_m=0,
       notes='Endemic in US southwest (rodent reservoir). Pneumonic form is the weaponization concern. Antibiotics within 24 hr of symptoms is critical.',
       sources=['CDC plague clinical guidance', 'USAMRIID Blue Book']),

    _a(id='botulinum', name='Botulinum Toxin (Clostridium botulinum)', category='biological',
       cas_number='', un_number='',
       hazards=['Tier 1 select agent', 'most potent toxin known'],
       physical_state='aerosol / ingested toxin',
       odor='none',
       idlh_ppm=None,
       symptoms='12-72 hr onset: symmetric descending flaccid paralysis — diplopia, dysphagia, dysarthria → respiratory failure. Patient stays alert.',
       route='inhalation / ingestion / wound',
       decon='Soap + water. Toxin is inactivated by heat (85°C × 5 min) or 0.1% hypochlorite.',
       first_aid='Mechanical ventilation as paralysis ascends. Immediate antitoxin shortens duration.',
       antidote='Heptavalent Botulism Antitoxin (BAT-H7; CDC stockpile). Call CDC Emergency Ops (770-488-7100) 24/7.',
       ppe_level='Standard + surgical mask (not contagious person-to-person)',
       evac_distance_m=0,
       notes='Not contagious. Paralysis can persist weeks-months; ICU-level supportive care required.',
       sources=['CDC botulism clinical guidance', 'USAMRIID Blue Book']),

    # ─── Radiological ───
    _a(id='cs137', name='Cesium-137', category='radiological',
       cas_number='10045-97-3', un_number='2911',
       hazards=['gamma emitter', 'dirty-bomb candidate'],
       physical_state='solid (powder / pellet)',
       odor='none',
       idlh_ppm=None,
       symptoms='Acute Radiation Syndrome above ~1 Gy: nausea/vomiting, fatigue, later hematopoietic collapse. Localized contact burns from intense sources.',
       route='external gamma / inhalation / ingestion',
       decon='Strip + shower + soap/water. Collect runoff. Survey with gamma probe until < 2× background.',
       first_aid='Remove from source (time/distance/shielding). Decon externally. Treat conventional injuries first.',
       antidote='Prussian Blue (ferric hexacyanoferrate) PO for internal contamination — enhances fecal excretion.',
       ppe_level='Level C + dosimetry; Level A if respirable particulate suspected',
       evac_distance_m=100,
       notes='30-year half-life. Common in medical/industrial sources (Goiânia 1987). Prussian Blue is the specific countermeasure.',
       sources=['CDC Radiation Emergencies — Cesium-137', 'REMM (Radiation Emergency Medical Management)', 'IAEA Safety Reports']),

    _a(id='i131', name='Iodine-131', category='radiological',
       cas_number='10043-66-0', un_number='',
       hazards=['beta + gamma emitter', 'thyroid-seeking'],
       physical_state='gas / liquid / particulate',
       odor='none',
       idlh_ppm=None,
       symptoms='Thyroid ablation risk with high exposure. Low acute symptoms at typical fallout doses; long-latency thyroid cancer (esp. children).',
       route='inhalation / ingestion (milk, water, leafy greens)',
       decon='Strip + shower. Shelter-in-place effective for short half-life.',
       first_aid='Potassium iodide (KI) prophylaxis BEFORE or within hours of exposure blocks thyroid uptake.',
       antidote='Potassium iodide (adult 130 mg, child per FDA weight table). See CE-03 dosing entry.',
       ppe_level='N95/P100 for particulate; dosimetry',
       evac_distance_m=0,
       notes='8-day half-life — shelter-in-place often sufficient. Primary reactor-accident concern (Chernobyl, Fukushima). KI must be given before or shortly after exposure.',
       sources=['CDC KI Guidance', 'FDA KI dosing tables', 'REMM Iodine-131 fact sheet']),
]