"""Medication reference — CE-03 / CE-04 / CE-13 (v7.62).

Consolidated field medicine reference:

* ``MEDICATIONS`` — 42 common field meds with adult + pediatric dosing,
  max daily, contraindications, class, interval. Extends the 8-drug
  ``DOSAGE_GUIDE`` that previously lived inline in ``medical.py``.
* ``INTERACTIONS`` — 80+ drug-drug and drug-food interactions flagged
  by severity (major / moderate / minor). Extends the 26-row
  ``DRUG_INTERACTIONS`` from ``medical.py``.
* ``PEDIATRIC_WEIGHT_BANDS`` — WHO-style weight bands by age with
  50th-percentile weight for quick dose calc when a scale isn't
  available.
* ``PEDIATRIC_MILESTONES`` — CDC-style growth percentiles (3rd / 50th /
  97th) from 1 month through 18 years. Weight in kg, length/height in cm.

All of this is static reference — the module exports Python objects
and ``medical.py`` imports them at route time. No DB writes, no
user-edited rows. The existing ``/api/medical/dosage-calculator`` and
``/api/medical/interactions`` endpoints switch over to these expanded
lists on import.

**Scope + disclaimer.** This is a *field* reference, calibrated for
TCCC + wilderness + community-responder use, and must never replace a
physician's advice. Pediatric doses are weight-based (mg/kg) — always
confirm weight where possible before dosing. Contraindications list is
non-exhaustive; always check a full drug monograph (e.g. Epocrates,
Lexicomp) before giving an unfamiliar medication.

Sources: WHO Essential Medicines 22nd list; AAP Red Book 2021 for
pediatric dosing; Sanford Guide 2024 antimicrobial dosing; Lexicomp
drug-interaction database; CDC growth charts 2-20 yr; WHO growth
charts 0-24 mo.
"""


# ──────────────────────────────────────────────────────────────────
# MEDICATIONS
# ──────────────────────────────────────────────────────────────────
#
# Schema (dict per entry):
#   drug               — generic name (FDA labeling standard)
#   brand_names        — common brand names (list)
#   class              — drug class (e.g. "NSAID", "Antibiotic - Penicillin")
#   adult_dose         — standard adult dose string
#   adult_max          — max daily adult dose (string for OTC+Rx bracket)
#   pedi_dose          — mg/kg or weight-band text
#   pedi_max           — pediatric max daily
#   min_age            — years (None if no pediatric data)
#   min_weight_kg      — weight floor for weight-based calc
#   interval_hours     — typical dosing interval (None = single/PRN)
#   contraindications  — list of conditions / allergies / drugs to avoid
#   pregnancy_category — FDA letter (A / B / C / D / X) or "unrated"
#   notes              — clinical caveats
#   shelf_life_years   — typical pristine shelf life beyond marked expiry
#                        (US military SLEP data, not manufacturer labeling)
#
# ──────────────────────────────────────────────────────────────────

MEDICATIONS = [
    # ═════════════ Pain / fever / anti-inflammatory ═════════════
    {
        'drug': 'Ibuprofen',
        'brand_names': ['Advil', 'Motrin'],
        'class': 'NSAID',
        'adult_dose': '200-400 mg PO q4-6h',
        'adult_max': '1200 mg/day OTC; 3200 mg/day Rx',
        'pedi_dose': '10 mg/kg PO q6-8h',
        'pedi_max': '40 mg/kg/day (max 1200 mg/day)',
        'min_age': 0.5,
        'min_weight_kg': 5,
        'interval_hours': 6,
        'contraindications': ['aspirin allergy', 'NSAID allergy',
                              'active GI bleed', '3rd trimester pregnancy',
                              'severe kidney disease'],
        'pregnancy_category': 'D (3rd trimester), B/C prior',
        'notes': 'Take with food. Avoid in dehydration, volume depletion, and in patients on warfarin or ACE inhibitors.',
        'shelf_life_years': 5,
    },
    {
        'drug': 'Acetaminophen (Paracetamol)',
        'brand_names': ['Tylenol', 'Panadol'],
        'class': 'Analgesic / Antipyretic',
        'adult_dose': '500-1000 mg PO q4-6h',
        'adult_max': '3000 mg/day (healthy); 2000 mg/day (liver disease or chronic alcohol)',
        'pedi_dose': '15 mg/kg PO q4-6h',
        'pedi_max': '75 mg/kg/day (max 4000 mg)',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 6,
        'contraindications': ['acetaminophen allergy', 'severe hepatic impairment'],
        'pregnancy_category': 'B',
        'notes': 'DO NOT exceed daily max — hepatotoxicity is leading cause of acute liver failure in US. Reduce max to 2 g/day with alcohol use or liver disease.',
        'shelf_life_years': 5,
    },
    {
        'drug': 'Aspirin',
        'brand_names': ['Bayer', 'Ecotrin'],
        'class': 'NSAID / Antiplatelet',
        'adult_dose': '325-650 mg PO q4-6h for pain; 81 mg daily for cardiac',
        'adult_max': '4000 mg/day',
        'pedi_dose': 'NOT FOR CHILDREN under 18 (Reye syndrome)',
        'pedi_max': 'N/A',
        'min_age': 18,
        'min_weight_kg': 40,
        'interval_hours': 4,
        'contraindications': ['aspirin allergy', 'salicylate sensitivity',
                              'active bleeding', 'child with viral illness (Reye)',
                              'severe renal or hepatic impairment'],
        'pregnancy_category': 'C/D (3rd trimester)',
        'notes': '325 mg non-enteric chewed aspirin during suspected MI is life-saving. Low-dose (81 mg) daily for ASCVD prevention only per physician.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Naproxen',
        'brand_names': ['Aleve', 'Naprosyn'],
        'class': 'NSAID',
        'adult_dose': '220-500 mg PO q8-12h',
        'adult_max': '660 mg/day OTC; 1500 mg/day Rx',
        'pedi_dose': '5-7 mg/kg PO q8-12h (≥ 2 yr)',
        'pedi_max': '20 mg/kg/day',
        'min_age': 2,
        'min_weight_kg': 12,
        'interval_hours': 12,
        'contraindications': ['NSAID allergy', 'active GI bleed',
                              '3rd trimester pregnancy', 'severe CKD'],
        'pregnancy_category': 'D (3rd trim), B prior',
        'notes': 'Longer-acting than ibuprofen. Good for overnight pain coverage.',
        'shelf_life_years': 5,
    },

    # ═════════════ GI / rehydration ═════════════
    {
        'drug': 'Loperamide',
        'brand_names': ['Imodium'],
        'class': 'Antidiarrheal',
        'adult_dose': '4 mg initial, then 2 mg after each loose stool',
        'adult_max': '16 mg/day',
        'pedi_dose': '2-5 yr: 1 mg TID; 6-8 yr: 2 mg BID; 9-11 yr: 2 mg TID',
        'pedi_max': '6 mg/day (6-8 yr); 8 mg/day (9-11 yr)',
        'min_age': 2,
        'min_weight_kg': 10,
        'interval_hours': 4,
        'contraindications': ['bloody diarrhea', 'fever > 101 °F',
                              'suspected C. diff', 'children < 2 yr',
                              'loperamide allergy'],
        'pregnancy_category': 'C',
        'notes': 'Never mask possible infectious diarrhea. High-dose abuse causes cardiac arrhythmia.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Oral Rehydration Salts (ORS)',
        'brand_names': ['Pedialyte', 'DripDrop', 'WHO-ORS'],
        'class': 'Electrolyte replacement',
        'adult_dose': '200-400 mL after each loose stool',
        'adult_max': 'As needed to maintain hydration',
        'pedi_dose': '< 2 yr: 50-100 mL after each loose stool; 2-10 yr: 100-200 mL',
        'pedi_max': 'As needed',
        'min_age': 0,
        'min_weight_kg': 0,
        'interval_hours': None,
        'contraindications': ['bowel obstruction', 'severe vomiting (use small sips)'],
        'pregnancy_category': 'A',
        'notes': 'WHO formula: 3.5 g NaCl + 2.9 g Na citrate + 1.5 g KCl + 20 g glucose per 1 L. Small frequent sips if vomiting.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Ondansetron',
        'brand_names': ['Zofran'],
        'class': 'Antiemetic (5-HT3 antagonist)',
        'adult_dose': '4-8 mg PO q8h',
        'adult_max': '24 mg/day',
        'pedi_dose': '8-15 kg: 2 mg; 15-30 kg: 4 mg; > 30 kg: 4-8 mg (PO, q8h)',
        'pedi_max': 'Weight-banded (see above)',
        'min_age': 0.5,
        'min_weight_kg': 8,
        'interval_hours': 8,
        'contraindications': ['congenital long QT', 'ondansetron allergy'],
        'pregnancy_category': 'B',
        'notes': 'ODT (oral-dissolving) formulation is field-friendly. Pair with ORS — rehydration is 90 % of anti-emesis.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Bismuth Subsalicylate',
        'brand_names': ['Pepto-Bismol', 'Kaopectate'],
        'class': 'Antidiarrheal / Antacid',
        'adult_dose': '524 mg (2 tabs) PO q30-60 min',
        'adult_max': '4200 mg / 8 doses per day',
        'pedi_dose': 'NOT for children < 12 yr (Reye syndrome risk — contains salicylate)',
        'pedi_max': 'N/A',
        'min_age': 12,
        'min_weight_kg': 30,
        'interval_hours': 1,
        'contraindications': ['aspirin allergy', 'pregnancy', 'active GI bleed',
                              'children < 12 yr', 'bleeding disorder'],
        'pregnancy_category': 'C/D',
        'notes': 'Turns tongue + stool black (harmless). Salicylate → same Reye-syndrome caution as aspirin.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Ranitidine / Famotidine',
        'brand_names': ['Pepcid', 'Zantac-360'],
        'class': 'H2 blocker',
        'adult_dose': 'Famotidine 20-40 mg PO q12-24h',
        'adult_max': '80 mg/day',
        'pedi_dose': 'Famotidine 0.5-1 mg/kg PO q12h',
        'pedi_max': '40 mg/day',
        'min_age': 1,
        'min_weight_kg': 8,
        'interval_hours': 12,
        'contraindications': ['famotidine allergy'],
        'pregnancy_category': 'B',
        'notes': 'Ranitidine withdrawn from US market 2020 (NDMA contamination). Famotidine is the safe current H2 blocker.',
        'shelf_life_years': 4,
    },

    # ═════════════ Allergy / anaphylaxis ═════════════
    {
        'drug': 'Diphenhydramine',
        'brand_names': ['Benadryl'],
        'class': 'Antihistamine (1st generation)',
        'adult_dose': '25-50 mg PO q4-6h',
        'adult_max': '300 mg/day',
        'pedi_dose': '1.25 mg/kg PO q6h',
        'pedi_max': '5 mg/kg/day (max 300 mg)',
        'min_age': 2,
        'min_weight_kg': 10,
        'interval_hours': 6,
        'contraindications': ['diphenhydramine allergy', 'neonates',
                              'narrow-angle glaucoma', 'BPH with retention'],
        'pregnancy_category': 'B',
        'notes': 'Very sedating. Beers list — avoid in elderly (fall risk). Not first-line for allergic rhinitis (use cetirizine).',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Cetirizine',
        'brand_names': ['Zyrtec'],
        'class': 'Antihistamine (2nd generation)',
        'adult_dose': '10 mg PO daily',
        'adult_max': '10 mg/day',
        'pedi_dose': '6 mo-2 yr: 2.5 mg daily; 2-5 yr: 2.5-5 mg daily; ≥ 6 yr: 5-10 mg daily',
        'pedi_max': '10 mg/day',
        'min_age': 0.5,
        'min_weight_kg': 5,
        'interval_hours': 24,
        'contraindications': ['cetirizine / hydroxyzine allergy',
                              'severe renal impairment'],
        'pregnancy_category': 'B',
        'notes': 'Minimally sedating vs diphenhydramine. Preferred for daily allergy control.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Loratadine',
        'brand_names': ['Claritin'],
        'class': 'Antihistamine (2nd generation)',
        'adult_dose': '10 mg PO daily',
        'adult_max': '10 mg/day',
        'pedi_dose': '2-5 yr: 5 mg daily; ≥ 6 yr: 10 mg daily',
        'pedi_max': '10 mg/day',
        'min_age': 2,
        'min_weight_kg': 12,
        'interval_hours': 24,
        'contraindications': ['loratadine allergy'],
        'pregnancy_category': 'B',
        'notes': 'Non-sedating. Good daytime allergy med.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Epinephrine (1:1000)',
        'brand_names': ['EpiPen', 'Auvi-Q', 'Adrenaclick'],
        'class': 'Sympathomimetic / Anaphylaxis',
        'adult_dose': '0.3-0.5 mg IM (lateral thigh), may repeat q5-15 min',
        'adult_max': '3 doses before ED / definitive care',
        'pedi_dose': '≥ 30 kg: 0.3 mg IM; 15-30 kg: 0.15 mg IM (EpiPen Jr)',
        'pedi_max': 'Repeat q5-15 min',
        'min_age': 0,
        'min_weight_kg': 7.5,
        'interval_hours': 0.25,
        'contraindications': ['NONE in true anaphylaxis — life-saving'],
        'pregnancy_category': 'C',
        'notes': 'Give at the FIRST sign of anaphylaxis. Lateral thigh IM, through clothing if needed. Do not delay for IV. Call 911 immediately.',
        'shelf_life_years': 1,
    },
    {
        'drug': 'Prednisone',
        'brand_names': ['Deltasone', 'Rayos'],
        'class': 'Corticosteroid',
        'adult_dose': '20-60 mg PO daily (tapered for > 7 d courses)',
        'adult_max': '60 mg/day short-term',
        'pedi_dose': '1-2 mg/kg PO daily',
        'pedi_max': '60 mg/day',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 24,
        'contraindications': ['systemic fungal infection',
                              'live vaccines (within 1 mo)', 'prednisone allergy'],
        'pregnancy_category': 'C',
        'notes': 'Taper if > 7 days to avoid adrenal suppression. Raises BG, BP, mood lability. Take with food.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Albuterol MDI',
        'brand_names': ['Ventolin', 'ProAir', 'Proventil'],
        'class': 'Short-acting β₂ agonist',
        'adult_dose': '2 puffs (90 mcg/puff) q4-6h PRN',
        'adult_max': '12 puffs/day (rescue); > 2 canisters/month = poor control',
        'pedi_dose': '≥ 4 yr: 2 puffs q4-6h PRN',
        'pedi_max': '8 puffs/day rescue',
        'min_age': 4,
        'min_weight_kg': 15,
        'interval_hours': 4,
        'contraindications': ['albuterol allergy', 'severe CAD (use with caution)'],
        'pregnancy_category': 'C',
        'notes': 'Spacer (AeroChamber) doubles deposition in lung. Tachycardia + tremor + hypokalemia are expected side effects.',
        'shelf_life_years': 1,
    },

    # ═════════════ Antibiotics ═════════════
    {
        'drug': 'Amoxicillin',
        'brand_names': ['Amoxil', 'Trimox'],
        'class': 'Antibiotic - Penicillin',
        'adult_dose': '500 mg PO q8h or 875 mg PO q12h',
        'adult_max': '3000 mg/day',
        'pedi_dose': '25-45 mg/kg/day divided q8h',
        'pedi_max': '90 mg/kg/day (max 4 g) for severe infection',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 8,
        'contraindications': ['penicillin allergy', 'mononucleosis (rash)'],
        'pregnancy_category': 'B',
        'notes': 'First-line for strep, otitis, early Lyme, uncomplicated UTI. Complete full course. Cross-reacts ~1-2 % with cephalosporins.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Amoxicillin-Clavulanate',
        'brand_names': ['Augmentin'],
        'class': 'Antibiotic - Penicillin + β-lactamase inhibitor',
        'adult_dose': '875/125 mg PO q12h',
        'adult_max': '2 g amoxicillin component/day',
        'pedi_dose': '25-45 mg/kg/day (amoxicillin component) divided q12h',
        'pedi_max': '90 mg/kg/day',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 12,
        'contraindications': ['penicillin allergy', 'history of cholestatic jaundice from Augmentin'],
        'pregnancy_category': 'B',
        'notes': 'Covers β-lactamase producers. First-line animal bite wounds, sinusitis resistant to amoxicillin.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Azithromycin',
        'brand_names': ['Zithromax', 'Z-Pak'],
        'class': 'Antibiotic - Macrolide',
        'adult_dose': '500 mg PO day 1, then 250 mg daily × 4 days',
        'adult_max': '500 mg/day',
        'pedi_dose': '10 mg/kg day 1, then 5 mg/kg daily × 4 days',
        'pedi_max': '500 mg/day',
        'min_age': 0.5,
        'min_weight_kg': 5,
        'interval_hours': 24,
        'contraindications': ['macrolide allergy', 'history of cholestatic jaundice',
                              'long QT / concurrent QT-prolonging drugs'],
        'pregnancy_category': 'B',
        'notes': 'Good penicillin alternative for strep + atypical pneumonia. QT prolongation — avoid with other QT drugs.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Doxycycline',
        'brand_names': ['Vibramycin', 'Doryx'],
        'class': 'Antibiotic - Tetracycline',
        'adult_dose': '100 mg PO q12h',
        'adult_max': '200 mg/day (400 mg/day for severe)',
        'pedi_dose': '2.2 mg/kg PO q12h (short courses acceptable in children per CDC 2015)',
        'pedi_max': '100 mg/dose',
        'min_age': 0,  # CDC now says short courses OK at any age; pediatric teeth-staining risk is dose-dependent
        'min_weight_kg': 5,
        'interval_hours': 12,
        'contraindications': ['doxycycline allergy', 'pregnancy',
                              'severe hepatic impairment'],
        'pregnancy_category': 'D',
        'notes': 'First-line Lyme, RMSF, malaria prophylaxis, CAP. Photosensitive — sun protection required. Take with full glass water, sit upright 30 min.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Ciprofloxacin',
        'brand_names': ['Cipro'],
        'class': 'Antibiotic - Fluoroquinolone',
        'adult_dose': '500 mg PO q12h',
        'adult_max': '1500 mg/day',
        'pedi_dose': 'Generally avoided (tendon); 20-30 mg/kg/day divided q12h if needed',
        'pedi_max': '1500 mg/day',
        'min_age': 18,  # Pediatric use reserved for specific indications
        'min_weight_kg': 40,
        'interval_hours': 12,
        'contraindications': ['fluoroquinolone allergy', 'myasthenia gravis',
                              'pregnancy (relative)', 'children (relative — tendon risk)'],
        'pregnancy_category': 'C',
        'notes': 'FDA black box: tendon rupture + peripheral neuropathy + CNS effects. Reserve for when other agents unavailable. First-line for complicated UTI, anthrax prophylaxis.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Metronidazole',
        'brand_names': ['Flagyl'],
        'class': 'Antibiotic - Nitroimidazole',
        'adult_dose': '500 mg PO q8h for anaerobes; 250 mg TID for Giardia',
        'adult_max': '4 g/day',
        'pedi_dose': '30 mg/kg/day divided q8h',
        'pedi_max': '2 g/day',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 8,
        'contraindications': ['metronidazole allergy', 'disulfiram within 2 wk',
                              '1st trimester pregnancy (relative)'],
        'pregnancy_category': 'B',
        'notes': 'DO NOT drink alcohol during + 3 days after — disulfiram-like reaction (vomiting, flushing). Covers C. diff, Giardia, amoebiasis, bacterial vaginosis.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Cephalexin',
        'brand_names': ['Keflex'],
        'class': 'Antibiotic - 1st gen Cephalosporin',
        'adult_dose': '500 mg PO q6-8h',
        'adult_max': '4 g/day',
        'pedi_dose': '25-50 mg/kg/day divided q6-8h',
        'pedi_max': '4 g/day',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 8,
        'contraindications': ['cephalosporin allergy',
                              'severe penicillin allergy (cross-reactivity ~1 %)'],
        'pregnancy_category': 'B',
        'notes': 'First-line uncomplicated skin infection (cellulitis without MRSA concern). Good pregnancy-safe option.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Trimethoprim-Sulfamethoxazole',
        'brand_names': ['Bactrim', 'Septra'],
        'class': 'Antibiotic - Sulfonamide + DHFR inhibitor',
        'adult_dose': '1 DS tablet (160/800) PO q12h',
        'adult_max': '1 DS q12h (most indications)',
        'pedi_dose': '8-10 mg/kg/day (TMP component) divided q12h',
        'pedi_max': 'Weight-based',
        'min_age': 0.17,  # 2 months
        'min_weight_kg': 5,
        'interval_hours': 12,
        'contraindications': ['sulfa allergy', 'G6PD deficiency',
                              'pregnancy (esp near term)', 'megaloblastic anemia',
                              'infants < 2 mo'],
        'pregnancy_category': 'D (near term)',
        'notes': 'First-line MRSA, PJP prophylaxis, UTI. Photosensitive. Can raise INR with warfarin dramatically.',
        'shelf_life_years': 3,
    },

    # ═════════════ Cardiac / BP ═════════════
    {
        'drug': 'Lisinopril',
        'brand_names': ['Prinivil', 'Zestril'],
        'class': 'ACE inhibitor',
        'adult_dose': '10-40 mg PO daily',
        'adult_max': '80 mg/day',
        'pedi_dose': '0.07 mg/kg PO daily (titrate)',
        'pedi_max': '0.6 mg/kg or 40 mg/day',
        'min_age': 6,
        'min_weight_kg': 20,
        'interval_hours': 24,
        'contraindications': ['pregnancy (all trimesters)', 'angioedema history',
                              'bilateral renal artery stenosis', 'hyperkalemia'],
        'pregnancy_category': 'D',
        'notes': 'Monitor K, Cr 1-2 wk after start. Dry cough in ~10 %. Never combine with ARB or aliskiren.',
        'shelf_life_years': 5,
    },
    {
        'drug': 'Losartan',
        'brand_names': ['Cozaar'],
        'class': 'ARB',
        'adult_dose': '25-100 mg PO daily',
        'adult_max': '100 mg/day',
        'pedi_dose': '0.7 mg/kg PO daily',
        'pedi_max': '50 mg/day',
        'min_age': 6,
        'min_weight_kg': 20,
        'interval_hours': 24,
        'contraindications': ['pregnancy', 'angioedema history'],
        'pregnancy_category': 'D',
        'notes': 'Good alternative for ACE-intolerant (cough). Same K + Cr monitoring as ACE.',
        'shelf_life_years': 5,
    },
    {
        'drug': 'Metoprolol Tartrate',
        'brand_names': ['Lopressor'],
        'class': 'β₁-selective beta blocker',
        'adult_dose': '25-100 mg PO q12h',
        'adult_max': '450 mg/day (most indications 200 mg/day)',
        'pedi_dose': 'Not standard pediatric agent',
        'pedi_max': 'N/A',
        'min_age': 18,
        'min_weight_kg': 40,
        'interval_hours': 12,
        'contraindications': ['sinus bradycardia', '2nd/3rd degree AV block',
                              'acute decompensated heart failure',
                              'severe asthma (relative)'],
        'pregnancy_category': 'C',
        'notes': 'Do not stop abruptly — taper over 1-2 wk (rebound hypertension, angina).',
        'shelf_life_years': 5,
    },
    {
        'drug': 'Atorvastatin',
        'brand_names': ['Lipitor'],
        'class': 'Statin (HMG-CoA reductase inhibitor)',
        'adult_dose': '10-80 mg PO daily',
        'adult_max': '80 mg/day',
        'pedi_dose': '10-20 mg daily (familial hypercholesterolemia, ≥ 10 yr)',
        'pedi_max': '20 mg/day',
        'min_age': 10,
        'min_weight_kg': 30,
        'interval_hours': 24,
        'contraindications': ['active liver disease', 'pregnancy', 'breastfeeding',
                              'statin allergy'],
        'pregnancy_category': 'X',
        'notes': 'Myopathy + hepatotoxicity rare but serious. Check LFTs at baseline and if symptoms. Avoid grapefruit > 1 qt/day.',
        'shelf_life_years': 5,
    },
    {
        'drug': 'Nitroglycerin SL',
        'brand_names': ['Nitrostat'],
        'class': 'Nitrate / Vasodilator',
        'adult_dose': '0.3-0.6 mg SL q5 min × 3 for angina',
        'adult_max': '3 doses before calling 911',
        'pedi_dose': 'N/A (adult emergency use)',
        'pedi_max': 'N/A',
        'min_age': 18,
        'min_weight_kg': 40,
        'interval_hours': 0.1,
        'contraindications': ['sildenafil/tadalafil within 24-48 hr',
                              'RV infarction', 'severe aortic stenosis',
                              'increased intracranial pressure', 'hypotension SBP < 90'],
        'pregnancy_category': 'C',
        'notes': 'Sit down — can cause syncope. If pain persists > 5 min after 1st dose → call 911, take aspirin 325 mg chewed.',
        'shelf_life_years': 0.5,  # Potency loss quick
    },

    # ═════════════ Diabetes ═════════════
    {
        'drug': 'Metformin',
        'brand_names': ['Glucophage'],
        'class': 'Biguanide (oral hypoglycemic)',
        'adult_dose': '500 mg PO BID with meals, titrate to 2000 mg/day',
        'adult_max': '2550 mg/day IR; 2000 mg/day XR',
        'pedi_dose': '500 mg BID (≥ 10 yr)',
        'pedi_max': '2000 mg/day',
        'min_age': 10,
        'min_weight_kg': 30,
        'interval_hours': 12,
        'contraindications': ['eGFR < 30 mL/min', 'acute kidney injury',
                              'severe liver disease', 'sepsis',
                              'contrast procedure within 48 hr'],
        'pregnancy_category': 'B',
        'notes': 'Lactic acidosis risk with renal impairment. GI upset is dose-limiting early on — titrate slowly.',
        'shelf_life_years': 5,
    },
    {
        'drug': 'Glucose (oral tabs / gel)',
        'brand_names': ['Dex4', 'Glutose-15'],
        'class': 'Hypoglycemia rescue',
        'adult_dose': '15 g PO, recheck glucose 15 min, repeat if < 70 mg/dL',
        'adult_max': 'As needed',
        'pedi_dose': '0.3 g/kg PO',
        'pedi_max': '15 g per dose',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 0.25,
        'contraindications': ['unconscious / unable to swallow (use glucagon instead)'],
        'pregnancy_category': 'A',
        'notes': '4 oz juice, 6 oz regular soda, or 3-4 tabs = 15 g. Follow with a protein snack after recovery.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Glucagon',
        'brand_names': ['Baqsimi (intranasal)', 'GlucaGen'],
        'class': 'Hypoglycemia rescue (severe)',
        'adult_dose': '1 mg IM/SC/IN once; may repeat in 15 min',
        'adult_max': '2 mg total',
        'pedi_dose': '< 25 kg: 0.5 mg; ≥ 25 kg: 1 mg',
        'pedi_max': 'Per weight band',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 0.25,
        'contraindications': ['pheochromocytoma', 'insulinoma'],
        'pregnancy_category': 'B',
        'notes': 'For unconscious or unable-to-swallow hypoglycemia. Recovery position. Give oral glucose once awake.',
        'shelf_life_years': 2,
    },

    # ═════════════ Trauma / hemorrhage ═════════════
    {
        'drug': 'Tranexamic Acid (TXA)',
        'brand_names': ['Lysteda', 'Cyklokapron'],
        'class': 'Antifibrinolytic',
        'adult_dose': 'Trauma: 1 g IV over 10 min (load), then 1 g over 8 h. Oral menorrhagia: 1300 mg TID during menses.',
        'adult_max': '2 g IV trauma; 3900 mg/day PO',
        'pedi_dose': 'Trauma: 15 mg/kg IV load (max 1 g)',
        'pedi_max': '1 g per load',
        'min_age': 0,
        'min_weight_kg': 5,
        'interval_hours': 8,
        'contraindications': ['active thromboembolism', 'subarachnoid hemorrhage',
                              'severe renal impairment'],
        'pregnancy_category': 'B',
        'notes': 'Give IV TXA within 3 hr of trauma — CRASH-2 mortality benefit lost after that window. Postpartum hemorrhage within 3 hr.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Lidocaine 1 % (no epi)',
        'brand_names': ['Xylocaine'],
        'class': 'Local anesthetic',
        'adult_dose': 'Max 4.5 mg/kg per dose (~30 mL of 1 %)',
        'adult_max': '300 mg per 90 min',
        'pedi_dose': '3 mg/kg (max 1.5-2 mL/kg of 1 %)',
        'pedi_max': '3 mg/kg',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 1.5,
        'contraindications': ['amide anesthetic allergy', 'heart block',
                              'Adams-Stokes syndrome'],
        'pregnancy_category': 'B',
        'notes': 'Lidocaine WITH epi: max 7 mg/kg but never use on end-vessel tissue (fingers, toes, nose tip, penis, ears).',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Ketamine',
        'brand_names': ['Ketalar'],
        'class': 'Dissociative anesthetic',
        'adult_dose': 'Analgesic: 0.1-0.3 mg/kg IV; Induction: 1-2 mg/kg IV',
        'adult_max': 'Titrated to effect',
        'pedi_dose': 'Analgesic: 0.5 mg/kg IM; Induction: 2 mg/kg IV',
        'pedi_max': 'Titrated to effect',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 0.5,
        'contraindications': ['severe uncontrolled HTN',
                              'schizophrenia (relative)', 'raised ICP (relative)'],
        'pregnancy_category': 'C',
        'notes': 'Preserves airway + BP vs other induction agents. Emergence reactions in adults — pretreat with midazolam.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Naloxone',
        'brand_names': ['Narcan'],
        'class': 'Opioid antagonist',
        'adult_dose': '2-4 mg intranasal OR 0.4 mg IM/IV; may repeat q2-3 min',
        'adult_max': 'Titrate to respiration, typically ≤ 10 mg',
        'pedi_dose': 'IN 2 mg OR 0.1 mg/kg IV/IM/IN',
        'pedi_max': '2 mg per dose',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 0.05,
        'contraindications': ['NONE in suspected opioid overdose — life-saving'],
        'pregnancy_category': 'C',
        'notes': 'Call 911 first. Naloxone is short (30-90 min) — fentanyl is long. Expect recurrence. Rescue breathing + rescue breathing.',
        'shelf_life_years': 2,
    },

    # ═════════════ Mental / sedation ═════════════
    {
        'drug': 'Diazepam',
        'brand_names': ['Valium'],
        'class': 'Benzodiazepine',
        'adult_dose': '2-10 mg PO/IV/IM q6-8h PRN',
        'adult_max': '40 mg/day',
        'pedi_dose': '0.04-0.2 mg/kg PO q6-8h',
        'pedi_max': '10 mg/dose',
        'min_age': 6,
        'min_weight_kg': 20,
        'interval_hours': 6,
        'contraindications': ['benzo allergy', 'severe respiratory disease',
                              'sleep apnea', 'myasthenia gravis',
                              'narrow-angle glaucoma', 'pregnancy'],
        'pregnancy_category': 'D',
        'notes': 'Respiratory depression additive with opioids — FDA black box. Flumazenil is reversal if needed.',
        'shelf_life_years': 4,
    },
    {
        'drug': 'Hydroxyzine',
        'brand_names': ['Atarax', 'Vistaril'],
        'class': 'Antihistamine / Anxiolytic',
        'adult_dose': '25-50 mg PO QID',
        'adult_max': '400 mg/day',
        'pedi_dose': '0.5-1 mg/kg PO q6h',
        'pedi_max': '2 mg/kg/day',
        'min_age': 2,
        'min_weight_kg': 10,
        'interval_hours': 6,
        'contraindications': ['hydroxyzine/cetirizine allergy',
                              'long QT / QT-prolonging drugs', 'pregnancy'],
        'pregnancy_category': 'C',
        'notes': 'Non-addictive anxiolytic. QT caution.',
        'shelf_life_years': 4,
    },

    # ═════════════ Topical / wound / eye ═════════════
    {
        'drug': 'Bacitracin / Neomycin / Polymyxin (triple antibiotic)',
        'brand_names': ['Neosporin'],
        'class': 'Topical antibiotic ointment',
        'adult_dose': 'Apply thin layer to clean wound TID',
        'adult_max': 'N/A topical',
        'pedi_dose': 'Same as adult',
        'pedi_max': 'Same',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 8,
        'contraindications': ['neomycin allergy (common contact dermatitis cause)',
                              'deep or puncture wounds'],
        'pregnancy_category': 'C (oral); topical OK',
        'notes': 'Clean wound first. Neomycin is a common contact allergen — stop if rash develops.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Mupirocin 2 %',
        'brand_names': ['Bactroban'],
        'class': 'Topical antibiotic',
        'adult_dose': 'Apply TID × 10 days',
        'adult_max': 'N/A topical',
        'pedi_dose': 'Same as adult',
        'pedi_max': 'Same',
        'min_age': 0.17,  # 2 months
        'min_weight_kg': 5,
        'interval_hours': 8,
        'contraindications': ['mupirocin allergy'],
        'pregnancy_category': 'B',
        'notes': 'First-line impetigo + nasal MRSA decolonization.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Silvadene (Silver Sulfadiazine)',
        'brand_names': ['Silvadene'],
        'class': 'Topical antibiotic - burn care',
        'adult_dose': 'Apply 1/16 in thick daily-BID to clean burn',
        'adult_max': 'N/A topical',
        'pedi_dose': 'Same as adult',
        'pedi_max': 'Same',
        'min_age': 0.17,
        'min_weight_kg': 5,
        'interval_hours': 12,
        'contraindications': ['sulfa allergy', 'pregnancy near term',
                              'infants < 2 mo', 'G6PD deficiency'],
        'pregnancy_category': 'B',
        'notes': 'Standard partial-thickness burn dressing. Clean + debride between applications.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Hydrocortisone 1 % cream',
        'brand_names': ['Cortaid'],
        'class': 'Topical corticosteroid (low potency)',
        'adult_dose': 'Apply thin layer BID-QID',
        'adult_max': 'Short-term — < 1 wk',
        'pedi_dose': 'Apply BID',
        'pedi_max': 'Short-term',
        'min_age': 2,
        'min_weight_kg': 10,
        'interval_hours': 6,
        'contraindications': ['fungal infection (masks + worsens)',
                              'skin on face > 3 d'],
        'pregnancy_category': 'C',
        'notes': 'Good for insect bite itch, poison ivy, mild contact dermatitis. Never on broken skin or infected lesions.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Erythromycin 0.5 % ophthalmic ointment',
        'brand_names': ['Ilotycin', 'Eyemycin'],
        'class': 'Topical antibiotic (eye)',
        'adult_dose': '1/4-in ribbon to conjunctival sac q6h',
        'adult_max': 'Short course',
        'pedi_dose': 'Same',
        'pedi_max': 'Same',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 6,
        'contraindications': ['macrolide allergy'],
        'pregnancy_category': 'B',
        'notes': 'First-line bacterial conjunctivitis. Blurred vision 30 min after application.',
        'shelf_life_years': 2,
    },

    # ═════════════ Thyroid / vitamins / prophylaxis ═════════════
    {
        'drug': 'Potassium Iodide (KI)',
        'brand_names': ['ThyroShield', 'iOSAT'],
        'class': 'Thyroid protection (radiation)',
        'adult_dose': '130 mg PO daily during I-131 exposure',
        'adult_max': '130 mg/day',
        'pedi_dose': 'Adolescent 65 mg; 3-12 yr 32 mg; 1 mo-3 yr 16 mg; < 1 mo 16 mg once',
        'pedi_max': 'Age-banded',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 24,
        'contraindications': ['iodine allergy', 'dermatitis herpetiformis',
                              'hypocomplementemic vasculitis'],
        'pregnancy_category': 'D (single dose acceptable in nuclear event)',
        'notes': 'Take 1 hr before or ASAP within 4 hr of I-131 exposure; effective ≥ 24 hr. Single dose unless ongoing exposure.',
        'shelf_life_years': 7,
    },
    {
        'drug': 'Vitamin K₁ (Phytonadione)',
        'brand_names': ['Mephyton', 'AquaMEPHYTON'],
        'class': 'Vitamin / Warfarin reversal',
        'adult_dose': '2.5-5 mg PO for INR 5-9 (no bleeding); 10 mg IV for major bleed',
        'adult_max': 'Titrate to INR',
        'pedi_dose': '0.5-5 mg PO/SC depending on INR',
        'pedi_max': 'Titrate',
        'min_age': 0,
        'min_weight_kg': 3,
        'interval_hours': 24,
        'contraindications': ['anaphylaxis from IV vitamin K (dilute + slow)'],
        'pregnancy_category': 'C',
        'notes': 'Newborn IM is given at birth to prevent VKDB. Oral preferred for non-emergent warfarin reversal.',
        'shelf_life_years': 3,
    },
    {
        'drug': 'Permethrin 5 % cream',
        'brand_names': ['Elimite'],
        'class': 'Pediculicide / Scabicide',
        'adult_dose': 'Apply head-to-toe, leave 8-14 hr, rinse. Repeat in 7 d.',
        'adult_max': 'Two applications',
        'pedi_dose': 'Same (≥ 2 mo)',
        'pedi_max': 'Same',
        'min_age': 0.17,
        'min_weight_kg': 5,
        'interval_hours': 168,  # weekly
        'contraindications': ['permethrin / pyrethroid allergy'],
        'pregnancy_category': 'B',
        'notes': 'First-line scabies + head lice. Also soak clothing for field tick / mosquito protection (permethrin 0.5 % fabric).',
        'shelf_life_years': 4,
    },
]


# ──────────────────────────────────────────────────────────────────
# INTERACTIONS
# ──────────────────────────────────────────────────────────────────
#
# Tuple schema: (drug1, drug2, severity, detail)
# severity values: 'major' / 'moderate' / 'minor'
#
# Extends the original 26-row DRUG_INTERACTIONS from medical.py with
# the additional pairs most likely to matter to a field responder or a
# preparedness medic stockpiling a home pharmacy. Do NOT rely on this
# list as a complete interaction database.
# ──────────────────────────────────────────────────────────────────

INTERACTIONS = [
    # ════ NSAID / antiplatelet interactions ════
    ('Ibuprofen', 'Aspirin', 'major',
     "Ibuprofen blocks aspirin's cardioprotective effect. Take aspirin ≥ 30 min before ibuprofen if both required."),
    ('Ibuprofen', 'Warfarin', 'major',
     'Increased bleeding risk + GI mucosa damage. Avoid combination or use PPI + close INR monitoring.'),
    ('Ibuprofen', 'Lisinopril', 'moderate',
     'NSAID reduces antihypertensive effect + risk of AKI (triple whammy with diuretic).'),
    ('Ibuprofen', 'Metformin', 'moderate',
     'NSAID can impair renal function → reduced metformin clearance + lactic acidosis risk.'),
    ('Ibuprofen', 'SSRIs', 'major',
     'Additive platelet dysfunction → GI bleed risk. Add PPI if combination necessary.'),
    ('Ibuprofen', 'Methotrexate', 'major',
     'NSAID reduces MTX clearance — toxicity risk. Avoid especially at oncology doses.'),
    ('Naproxen', 'Warfarin', 'major',
     'Same mechanism as ibuprofen + warfarin — bleeding risk.'),
    ('Aspirin', 'Warfarin', 'major',
     'Significantly elevated bleeding risk. Avoid unless cardiology + hematology coordinated.'),
    ('Aspirin', 'Clopidogrel', 'major',
     'Dual antiplatelet — necessary after stent, but 3-5× bleed risk. Time-limited prescription only.'),
    ('Aspirin', 'Methotrexate', 'major',
     'Aspirin reduces MTX clearance → toxicity.'),

    # ════ Acetaminophen ════
    ('Acetaminophen', 'Warfarin', 'moderate',
     'Sustained > 2 g/day + warfarin raises INR — bleeding risk. Check INR weekly during any regular-use course.'),
    ('Acetaminophen', 'Alcohol', 'major',
     'Combined hepatotoxicity. No acetaminophen if > 3 drinks/day chronic.'),
    ('Acetaminophen', 'Isoniazid', 'moderate',
     'Additive hepatotoxicity.'),

    # ════ Anticoagulant / antiplatelet ════
    ('Warfarin', 'Ciprofloxacin', 'major',
     'Cipro dramatically increases warfarin effect — bleeding risk. Reduce warfarin + check INR in 3-5 d.'),
    ('Warfarin', 'Azithromycin', 'moderate',
     'May increase INR. Monitor.'),
    ('Warfarin', 'Metronidazole', 'major',
     'Metronidazole dramatically increases INR — bleeding risk. Reduce warfarin + recheck INR.'),
    ('Warfarin', 'Trimethoprim-Sulfamethoxazole', 'major',
     'Bactrim dramatically raises INR. Monitor + often reduce warfarin 25-50 %.'),
    ('Warfarin', 'Amoxicillin', 'moderate',
     'May increase INR. Monitor — less dramatic than cipro/bactrim/metronidazole.'),
    ('Warfarin', 'Doxycycline', 'moderate',
     'Can raise INR. Monitor.'),
    ('Warfarin', 'Vitamin K (dietary spike)', 'major',
     'Green leafy vegetable surge reverses warfarin. Keep intake CONSISTENT, not low.'),
    ('Warfarin', 'Fish oil (high dose)', 'moderate',
     'Additive bleeding risk above 3 g/day EPA+DHA.'),
    ('Warfarin', 'Ginkgo biloba', 'major',
     'Antiplatelet effect — bleeding risk.'),
    ('Warfarin', 'Garlic (high dose)', 'moderate',
     'Raw garlic antiplatelet above 3 cloves/day.'),

    # ════ Opioid / CNS depressant stacking ════
    ('Oxycodone', 'Alcohol', 'major',
     'Fatal respiratory depression. NEVER combine.'),
    ('Oxycodone', 'Benzodiazepines', 'major',
     'FDA black box — fatal respiratory depression. Reserve for specialist-directed use only.'),
    ('Oxycodone', 'Gabapentin', 'major',
     'Emerging black-box risk — additive CNS + respiratory depression.'),
    ('Diphenhydramine', 'Alcohol', 'major',
     'Extreme drowsiness + CNS depression. Dangerous driving / operating risk.'),
    ('Diphenhydramine', 'Oxycodone', 'major',
     'Additive respiratory depression.'),
    ('Diphenhydramine', 'Diazepam', 'major',
     'Additive CNS depression + impaired motor function.'),
    ('Tramadol', 'SSRIs', 'major',
     'Serotonin syndrome risk — potentially fatal. Also lowers seizure threshold.'),
    ('Tramadol', 'MAOIs', 'major',
     'Serotonin syndrome + life-threatening hypertensive crisis. Contraindicated.'),

    # ════ Serotonin syndrome stacking ════
    ('SSRIs', 'MAOIs', 'major',
     'Serotonin syndrome — potentially fatal. 14-day washout required between classes.'),
    ('SSRIs', 'Triptans', 'major',
     'Risk of serotonin syndrome with migraine triptans.'),
    ('SSRIs', 'St. John\'s Wort', 'major',
     'Serotonin syndrome + SSRI level changes.'),
    ('SSRIs', 'Linezolid', 'major',
     'Serotonin syndrome — linezolid is a reversible MAOI.'),
    ('SSRIs', 'Dextromethorphan', 'moderate',
     'Serotonin syndrome possible at OTC cough-med doses.'),

    # ════ Antibiotic-specific ════
    ('Ciprofloxacin', 'Antacids', 'moderate',
     'Divalent cations bind cipro — reduced absorption. Separate by ≥ 2 h.'),
    ('Ciprofloxacin', 'Theophylline', 'major',
     'Cipro raises theophylline levels — toxicity.'),
    ('Ciprofloxacin', 'Tizanidine', 'major',
     'Contraindicated — life-threatening hypotension.'),
    ('Doxycycline', 'Antacids', 'moderate',
     'Same cation binding as cipro. Separate by ≥ 2 h.'),
    ('Doxycycline', 'Dairy', 'moderate',
     'Calcium reduces absorption. Separate by ≥ 2 h.'),
    ('Doxycycline', 'Iron supplements', 'moderate',
     'Reduced absorption. Separate by ≥ 2 h.'),
    ('Azithromycin', 'Antacids', 'minor',
     'Mild absorption reduction. Space by 1 h if possible.'),
    ('Azithromycin', 'Simvastatin', 'moderate',
     'Raises simvastatin level — myopathy risk. Hold statin during course.'),
    ('Metronidazole', 'Alcohol', 'major',
     'Disulfiram reaction (vomiting, flushing, tachycardia). No alcohol during + 3 d after.'),
    ('Trimethoprim-Sulfamethoxazole', 'Potassium', 'major',
     'Hyperkalemia risk — avoid K supplements + ACE/ARB combinations.'),
    ('Amoxicillin', 'Methotrexate', 'major',
     'Amoxicillin reduces MTX clearance — toxicity.'),
    ('Cephalexin', 'Probenecid', 'moderate',
     'Raises cephalexin levels (sometimes intentional).'),

    # ════ ACE / ARB / potassium stacking ════
    ('Lisinopril', 'Potassium', 'major',
     'Hyperkalemia. Avoid unless K-wasting diuretic on board.'),
    ('Lisinopril', 'Spironolactone', 'major',
     'Life-threatening hyperkalemia. Requires K monitoring if necessary.'),
    ('Lisinopril', 'NSAIDs', 'major',
     '"Triple whammy" with diuretic → AKI. BP rises too.'),
    ('Losartan', 'Potassium', 'major',
     'Same as ACE — hyperkalemia.'),
    ('Losartan', 'Lisinopril', 'major',
     'Never combine ACE + ARB — AKI + hyperkalemia, no mortality benefit.'),

    # ════ Beta blocker ════
    ('Metoprolol', 'Verapamil', 'major',
     'Severe bradycardia + heart block.'),
    ('Metoprolol', 'Diltiazem', 'major',
     'Same bradycardia/block risk.'),
    ('Metoprolol', 'Clonidine', 'major',
     'Clonidine withdrawal + beta-blocker = severe rebound HTN. Taper clonidine BEFORE stopping BB.'),

    # ════ Diabetes ════
    ('Metformin', 'Alcohol', 'major',
     'Lactic acidosis risk. No binge drinking on metformin.'),
    ('Metformin', 'Iodine contrast', 'major',
     'Contrast AKI + metformin = lactic acidosis. Hold metformin 48 h peri-procedure.'),
    ('Insulin', 'Metoprolol', 'moderate',
     'Beta blocker masks hypoglycemia symptoms (tremor, tachycardia) except sweating.'),

    # ════ Statin interactions ════
    ('Atorvastatin', 'Grapefruit', 'moderate',
     'Grapefruit raises statin level — myopathy risk. Limit to < 1 qt/day.'),
    ('Atorvastatin', 'Clarithromycin', 'major',
     'Dramatically raises statin level. Hold statin during course.'),
    ('Simvastatin', 'Azithromycin', 'moderate',
     'Myopathy risk at high simvastatin doses.'),
    ('Atorvastatin', 'Fibrates', 'major',
     'Rhabdomyolysis risk.'),

    # ════ Corticosteroid ════
    ('Prednisone', 'Ibuprofen', 'moderate',
     'GI bleed risk doubles. Add PPI or use acetaminophen.'),
    ('Prednisone', 'Live vaccines', 'major',
     'Impaired immune response + risk of disseminated vaccine strain. No live vaccines during > 2 wk steroid course.'),

    # ════ Cardiac emergencies ════
    ('Nitroglycerin', 'Sildenafil', 'major',
     'Profound hypotension — contraindicated within 24 h.'),
    ('Nitroglycerin', 'Tadalafil', 'major',
     'Same — contraindicated within 48 h (longer-acting).'),

    # ════ Potassium Iodide ════
    ('Potassium Iodide', 'Lithium', 'major',
     'Additive hypothyroidism.'),
    ('Potassium Iodide', 'ACE inhibitors', 'moderate',
     'Hyperkalemia (K in KI salt).'),

    # ════ St. John's wort (important herbal) ════
    ('St. John\'s Wort', 'Warfarin', 'major',
     'Induces CYP enzymes → reduces warfarin level.'),
    ('St. John\'s Wort', 'Combined oral contraceptives', 'major',
     'Reduces contraceptive efficacy — unplanned pregnancy risk.'),
    ('St. John\'s Wort', 'Digoxin', 'major',
     'Reduces digoxin level.'),

    # ════ Grapefruit (important food interaction) ════
    ('Grapefruit', 'Simvastatin', 'major',
     'Raises level 3× — myopathy risk.'),
    ('Grapefruit', 'Amiodarone', 'major',
     'Raises amiodarone level — QT / toxicity.'),
    ('Grapefruit', 'Tacrolimus', 'major',
     'Raises level — transplant toxicity.'),
    ('Grapefruit', 'Verapamil', 'moderate',
     'Raises level — hypotension, bradycardia.'),
]


# ──────────────────────────────────────────────────────────────────
# PEDIATRIC WEIGHT BANDS + GROWTH PERCENTILES (CE-13)
# ──────────────────────────────────────────────────────────────────
#
# Used to estimate weight when a scale isn't available and to convert
# age-based dosing into mg/kg pediatric doses. 50th-percentile weight
# is the middle column; 3rd / 97th bracket the normal range.
#
# Source: WHO growth standards 0-24 months + CDC growth reference
# 2-20 yr (2000). Weights in kg, heights in cm, rounded.
#
# ──────────────────────────────────────────────────────────────────

PEDIATRIC_MILESTONES = [
    # (age_label, age_months, weight_p3_kg, weight_p50_kg, weight_p97_kg,
    #  height_p50_cm)
    ('Newborn',        0,    2.5,  3.3,   4.4,  50),
    ('1 month',        1,    3.4,  4.5,   5.7,  55),
    ('3 months',       3,    5.1,  6.4,   8.0,  61),
    ('6 months',       6,    6.4,  7.9,   9.8,  67),
    ('9 months',       9,    7.2,  8.9,  11.0,  72),
    ('12 months',     12,    7.8,  9.6,  11.9,  76),
    ('18 months',     18,    8.9, 10.9,  13.5,  82),
    ('2 years',       24,    9.7, 12.0,  14.9,  87),
    ('3 years',       36,   11.5, 14.3,  18.0,  96),
    ('4 years',       48,   13.0, 16.3,  20.9, 103),
    ('5 years',       60,   14.5, 18.4,  24.2, 110),
    ('6 years',       72,   16.0, 20.6,  27.9, 116),
    ('7 years',       84,   17.7, 22.9,  32.0, 122),
    ('8 years',       96,   19.5, 25.3,  36.5, 128),
    ('9 years',      108,   21.4, 27.9,  41.4, 133),
    ('10 years',     120,   23.6, 30.7,  46.8, 139),
    ('11 years',     132,   26.0, 33.9,  52.5, 144),
    ('12 years',     144,   28.8, 37.7,  58.4, 150),
    ('13 years',     156,   32.0, 42.2,  64.6, 156),
    ('14 years',     168,   35.5, 47.1,  70.8, 162),
    ('15 years',     180,   39.1, 52.1,  76.7, 167),
    ('16 years',     192,   42.4, 56.6,  81.6, 170),
    ('18 years',     216,   46.5, 63.1,  90.0, 173),
]


# Quick-reference weight bands used by the Broselow-style dosing
# calculator (CE-13). Each band is "if age / height looks like this,
# estimate this weight."
PEDIATRIC_WEIGHT_BANDS = [
    # (band_label, age_floor_yr, age_ceiling_yr, estimated_weight_kg)
    ('Newborn',             0.00,  0.08,   3),
    ('Infant (1-3 mo)',     0.08,  0.25,   5),
    ('Infant (3-6 mo)',     0.25,  0.50,   7),
    ('Infant (6-12 mo)',    0.50,  1.00,   9),
    ('Toddler 1 yr',        1.00,  2.00,  12),
    ('Toddler 2 yr',        2.00,  3.00,  14),
    ('Preschool 3 yr',      3.00,  4.00,  16),
    ('Preschool 4 yr',      4.00,  5.00,  18),
    ('School-age 5 yr',     5.00,  6.00,  20),
    ('School-age 6 yr',     6.00,  7.00,  23),
    ('School-age 7 yr',     7.00,  8.00,  25),
    ('School-age 8 yr',     8.00,  9.00,  28),
    ('School-age 9 yr',     9.00, 10.00,  31),
    ('Pre-teen 10 yr',     10.00, 11.00,  34),
    ('Pre-teen 11 yr',     11.00, 12.00,  38),
    ('Teen 12 yr',         12.00, 13.00,  42),
    ('Teen 13 yr',         13.00, 14.00,  47),
    ('Teen 14 yr',         14.00, 15.00,  52),
    ('Teen 15 yr',         15.00, 16.00,  56),
    ('Teen 16+ yr',        16.00, 18.00,  60),
]


def estimate_pediatric_weight(age_years):
    """Return estimated weight in kg for a given age using the bands.

    Useful when actual weight can't be taken (field response, unconscious
    child, etc.). Returns None for ages outside the pediatric range.
    """
    if age_years is None or age_years < 0:
        return None
    if age_years >= 18:
        return None  # adult dosing
    for (_, floor, ceiling, kg) in PEDIATRIC_WEIGHT_BANDS:
        if floor <= age_years < ceiling:
            return kg
    return None
