"""
Curated survival & preparedness content catalog.
171 YouTube channels across 20 categories, sourced from SURVIVAL-YOUTUBE-REFERENCE.md.
37 individual tutorial videos + 12 audio training entries.
"""

# ─── YouTube Channel Catalog (171 channels, 20 categories) ─────────────────

CHANNEL_CATALOG = [
    # Wilderness Survival & Bushcraft
    {'name': 'Primitive Technology', 'focus': 'Pure primitive builds, no tools, no dialogue (10M+)', 'url': 'https://www.youtube.com/@primitivetechnology9550', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Dave Canterbury', 'focus': "10 C's of Survival, bushcraft, self-reliance (700K+)", 'url': 'https://www.youtube.com/@DaveCanterbury', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Survival Lilly', 'focus': 'Shelter, fire, foraging, water purification (2M+)', 'url': 'https://www.youtube.com/@SurvivalLilly', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Joe Robinet', 'focus': 'Solo bushcraft camping, shelter building (1.5M+)', 'url': 'https://www.youtube.com/@JoeRobinet', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Corporals Corner', 'focus': 'Military-style bushcraft, detailed tutorials (900K+)', 'url': 'https://www.youtube.com/@CorporalsCorner', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Far North Bushcraft and Survival', 'focus': 'Alaska wilderness, wild edibles, natural medicine (1M+)', 'url': 'https://www.youtube.com/@FarNorthBushcraftAndSurvival', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'My Self Reliance', 'focus': 'Off-grid cabin building, Canadian wilderness', 'url': 'https://www.youtube.com/@MySelfReliance', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'TA Outdoors', 'focus': 'Shelter builds, Viking houses, DIY (2.5M)', 'url': 'https://www.youtube.com/@TAOutdoors', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Coalcracker Bushcraft', 'focus': 'Primitive skills, friction fire, stone tools', 'url': 'https://www.youtube.com/@CoalcrackerBushcraft', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'MCQBushcraft', 'focus': 'UK bushcraft, fire craft, cinematography', 'url': 'https://www.youtube.com/@MCQBushcraft', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Native Survival', 'focus': 'ALONE finalist, primitive living', 'url': 'https://www.youtube.com/@NativeSurvival', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': "Fowler's Makery and Mischief", 'focus': 'ALONE S3 winner, catch-and-cook, off-grid', 'url': 'https://www.youtube.com/@FowlersMakeryandMischief', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Sigma 3 Survival School', 'focus': 'Comprehensive survival video encyclopedia', 'url': 'https://www.youtube.com/@Sigma3SurvivalSchool', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Frontier Bushcraft', 'focus': 'Shelter building, fire craft instruction', 'url': 'https://www.youtube.com/@FrontierBushcraft', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Bertram - Craft and Wilderness', 'focus': 'Blacksmithing, structures, primitive fishing', 'url': 'https://www.youtube.com/@BertramCraftandWilderness', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Wargeh Bushcraft', 'focus': 'Winter camping, log cabins, off-grid', 'url': 'https://www.youtube.com/@WargehBushcraft', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Tom McElroy', 'focus': 'In-depth survival guides', 'url': 'https://www.youtube.com/@TomMcElroyWildSurvival', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Donny Dust', 'focus': 'USMC vet, primitive survival, world travel', 'url': 'https://www.youtube.com/@PaleoTracks', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Smooth Gefixt', 'focus': 'Weekly survival challenges, friction fire', 'url': 'https://www.youtube.com/@SmoothGefixt', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'AlfieAesthetics', 'focus': 'Short, informative bushcraft, foraging, nav', 'url': 'https://www.youtube.com/@AlfieAesthetics', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Survival Russia', 'focus': 'Extreme cold weather, Russian wilderness', 'url': 'https://www.youtube.com/@SurvivalRussia', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Ultimate Survival Tips', 'focus': 'Knives, bows, outdoor survival', 'url': 'https://www.youtube.com/@UltimateSurvivalTips', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'School of Self Reliance', 'focus': 'Comprehensive wilderness self-reliance', 'url': 'https://www.youtube.com/@SchoolOfSelfReliance', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Prepared Mind 101', 'focus': 'Bushcraft, urban, wilderness + reviews', 'url': 'https://www.youtube.com/@PreparedMind101', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'The Wooded Beardsman', 'focus': 'Canadian bushcraft, cold-weather, gear', 'url': 'https://www.youtube.com/@TheWoodedBeardsman', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Zed Outdoors', 'focus': 'Bushcraft, natural crafts, homesteading', 'url': 'https://www.youtube.com/@ZedOutdoors', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Wranglerstar', 'focus': 'Cabin building, blacksmithing, self-reliance', 'url': 'https://www.youtube.com/@waborita', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Bushradical', 'focus': '30-day cabin builds, simplicity', 'url': 'https://www.youtube.com/@Bushradical', 'category': 'Wilderness Survival & Bushcraft'},
    # Wild Edible Plants & Foraging
    {'name': 'Learn Your Land', 'focus': 'Mushrooms, plant ID, wild food/medicine', 'url': 'https://www.youtube.com/@LearnYourLand', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Eat The Weeds', 'focus': 'Wild edible identification, recipes', 'url': 'https://www.youtube.com/@EatTheWeeds', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Edible Wild Food', 'focus': 'Plants, trees, fungi identification', 'url': 'https://www.youtube.com/@EdibleWildFood', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'North Spore', 'focus': 'Mushroom growing, foraging, fungi', 'url': 'https://www.youtube.com/@NorthSpore', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Feral Foraging', 'focus': 'Fundamental foraging skills', 'url': 'https://www.youtube.com/@FeralForaging', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'The3foragers', 'focus': 'Wild edibles, mushroom foraging', 'url': 'https://www.youtube.com/@the3foragers', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Return to Nature', 'focus': 'Foraging, herbalism, mushroom hunting', 'url': 'https://www.youtube.com/@ReturnToNature', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Forage + Feast', 'focus': 'Wild plants, mushrooms, natural foods', 'url': 'https://www.youtube.com/@ForageAndFeast', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Outdoor Chef Life', 'focus': 'Coastal foraging, seafood', 'url': 'https://www.youtube.com/@OutdoorChefLife', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Passionate Forager', 'focus': 'Dedicated mushroom foraging', 'url': 'https://www.youtube.com/@PassionateForager', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Morel Mushroom Hunting Club', 'focus': 'Mushroom foraging', 'url': 'https://www.youtube.com/@MorelMushroomHuntingClub', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Fungicopia', 'focus': 'Mushroom harvesting and foraging', 'url': 'https://www.youtube.com/@Fungicopia', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'EatYourBackyard', 'focus': 'Florida edible wild plants', 'url': 'https://www.youtube.com/@EatYourBackyard', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Chad Zuber', 'focus': 'Survival wild edibles, water', 'url': 'https://www.youtube.com/@ChadZuber', 'category': 'Wild Edible Plants & Foraging'},
    # Medicinal Plants & Wilderness First Aid
    {'name': 'Chestnut School of Herbal Medicine', 'focus': 'Medicine making, materia medica, plant walks', 'url': 'https://www.youtube.com/@ChestnutSchoolOfHerbalMedicine', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'Herbal Academy', 'focus': 'Art & science of plant medicine', 'url': 'https://www.youtube.com/@HerbalAcademy', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'Susun Weed', 'focus': 'Wise Woman tradition, 250+ remedy videos', 'url': 'https://www.youtube.com/@SusunWeed', 'category': 'Medicinal Plants & First Aid'},
    {'name': '7Song', 'focus': 'Plant monographs, first-aid herbalism', 'url': 'https://www.youtube.com/@7Song', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'HerbMentor', 'focus': 'Identifying, gathering, preparing wild plants', 'url': 'https://www.youtube.com/@HerbMentor', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'DrBones NurseAmy', 'focus': 'Survival medicine from MD + RN', 'url': 'https://www.youtube.com/@DrBonesNurseAmy', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'PrepMedic', 'focus': 'Flight paramedic, trauma kits, tactical medicine', 'url': 'https://www.youtube.com/@PrepMedic', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'Skinny Medic', 'focus': 'Medical gear, first aid training', 'url': 'https://www.youtube.com/@SkinnyMedic', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'Gray Bearded Green Beret', 'focus': 'First aid, Green Beret survival skills', 'url': 'https://www.youtube.com/@GrayBeardedGreenBeret', 'category': 'Medicinal Plants & First Aid'},
    # Food Preservation & Long-Term Storage
    {'name': 'Homesteading Family', 'focus': 'Canning, freeze-drying, garden preservation', 'url': 'https://www.youtube.com/@HomesteadingFamily', 'category': 'Food Preservation & Storage'},
    {'name': 'Roots and Refuge Farm', 'focus': 'Gardening, farm life, food preservation (600K+)', 'url': 'https://www.youtube.com/@RootsAndRefugeFarm', 'category': 'Food Preservation & Storage'},
    {'name': 'Melissa K. Norris', 'focus': 'Canning, dehydrating, fermenting, salt curing', 'url': 'https://www.youtube.com/@MelissaKNorris', 'category': 'Food Preservation & Storage'},
    {'name': "Becky's Homestead", 'focus': 'Self-sufficient lifestyle, food preservation', 'url': 'https://www.youtube.com/@BeckysHomestead', 'category': 'Food Preservation & Storage'},
    {'name': 'Gubba Homestead', 'focus': 'Garden, preserve, cook, herbal remedies', 'url': 'https://www.youtube.com/@GubbaHomestead', 'category': 'Food Preservation & Storage'},
    {'name': 'Arms Family Homestead', 'focus': 'Large-scale gardening, greenhouse, livestock', 'url': 'https://www.youtube.com/@ArmsFamilyHomestead', 'category': 'Food Preservation & Storage'},
    {'name': 'Justin Rhodes', 'focus': 'Permaculture, pastured livestock, daily vlogs', 'url': 'https://www.youtube.com/@JustinRhodes', 'category': 'Food Preservation & Storage'},
    {'name': 'Growing Your Greens', 'focus': 'Most-watched gardening channel on YouTube', 'url': 'https://www.youtube.com/@GrowingYourGreens', 'category': 'Food Preservation & Storage'},
    {'name': 'Living Web Farms', 'focus': 'Farming, food preservation education', 'url': 'https://www.youtube.com/@LivingWebFarms', 'category': 'Food Preservation & Storage'},
    {'name': 'Self-Sufficient Me', 'focus': 'Food production, garden, self-sufficiency', 'url': 'https://www.youtube.com/@SelfSufficientMe', 'category': 'Food Preservation & Storage'},
    {'name': 'Mother Earth News', 'focus': 'Sustainable living, traditional skills', 'url': 'https://www.youtube.com/@MotherEarthNews', 'category': 'Food Preservation & Storage'},
    # Prepper & Emergency Preparedness
    {'name': 'Canadian Prepper', 'focus': 'Gear reviews, current events, DIY projects (2M+)', 'url': 'https://www.youtube.com/@CanadianPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'City Prepping', 'focus': 'Urban/suburban survival, high production (1M+)', 'url': 'https://www.youtube.com/@CityPrepping', 'category': 'Prepper & Emergency Prep'},
    {'name': 'The Urban Prepper', 'focus': 'City survival, compact kits, family-friendly (500K+)', 'url': 'https://www.youtube.com/@TheUrbanPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Sensible Prepper', 'focus': 'Gear reviews, firearms, preparedness (1M+)', 'url': 'https://www.youtube.com/@SensiblePrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'The Provident Prepper', 'focus': 'Family preparedness, food/water storage (400K+)', 'url': 'https://www.youtube.com/@TheProvidentPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'SouthernPrepper1', 'focus': 'Homestead prepping, gardening, livestock (500K+)', 'url': 'https://www.youtube.com/@SouthernPrepper1', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Magic Prepper', 'focus': 'Gear deep-dives, post-collapse philosophy (300K+)', 'url': 'https://www.youtube.com/@MagicPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Bear Independent', 'focus': 'Food storage, self-defense, no-nonsense (300K+)', 'url': 'https://www.youtube.com/@BearIndependent', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Step One Survival', 'focus': 'Beginner-friendly, bug-out bags, basics (170K+)', 'url': 'https://www.youtube.com/@StepOneSurvival', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Survival Dispatch', 'focus': 'Expert collective, bite-sized tutorials (200K+)', 'url': 'https://www.youtube.com/@SurvivalDispatch', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Full Spectrum Survival', 'focus': 'Alert updates, crisis information (300K+)', 'url': 'https://www.youtube.com/@FullSpectrumSurvival', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Funky Prepper', 'focus': 'Former British Infantry, bug-out preps (100K+)', 'url': 'https://www.youtube.com/@FunkyPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'PREPSTEADING', 'focus': 'Prepping + homesteading intersection', 'url': 'https://www.youtube.com/@PREPSTEADING', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Last Line of Defense', 'focus': 'Gear reviews, survivalist focus (100K+)', 'url': 'https://www.youtube.com/@LastLineOfDefense', 'category': 'Prepper & Emergency Prep'},
    # Self-Defense & Security
    {'name': 'Active Self Protection', 'focus': 'Real-world self-defense analysis', 'url': 'https://www.youtube.com/@ActiveSelfProtection', 'category': 'Self-Defense & Security'},
    {'name': 'Warrior Poet Society', 'focus': 'Former Ranger, tactics + philosophy', 'url': 'https://www.youtube.com/@WarriorPoetSociety', 'category': 'Self-Defense & Security'},
    {'name': 'Hickok45', 'focus': 'Firearms safety, reviews, shooting', 'url': 'https://www.youtube.com/@hickok45', 'category': 'Self-Defense & Security'},
    {'name': 'Black Scout Survival', 'focus': 'Tactical + wilderness, lock picking', 'url': 'https://www.youtube.com/@BlackScoutSurvival', 'category': 'Self-Defense & Security'},
    {'name': 'Nutnfancy', 'focus': 'Gear reviews, tactical philosophy', 'url': 'https://www.youtube.com/@nutnfancy', 'category': 'Self-Defense & Security'},
    {'name': 'FieldCraft Survival', 'focus': 'Tactical skills, wet-weather fire', 'url': 'https://www.youtube.com/@FieldCraftSurvival', 'category': 'Self-Defense & Security'},
    {'name': 'Survival Gear', 'focus': 'Tactical & survival gear reviews (782K)', 'url': 'https://www.youtube.com/@SurvivalGear', 'category': 'Self-Defense & Security'},
    # Off-Grid Power & Energy
    {'name': 'DIY Solar Power (Will Prowse)', 'focus': 'DIY solar builds, gear reviews (1M+)', 'url': 'https://www.youtube.com/@WillProwse', 'category': 'Off-Grid Power & Energy'},
    {'name': 'Engineer775', 'focus': 'Off-grid systems, water, solar, heating', 'url': 'https://www.youtube.com/@Engineer775', 'category': 'Off-Grid Power & Energy'},
    {'name': 'Solar Power Edge', 'focus': 'Creative solar, high-tech survival', 'url': 'https://www.youtube.com/@SolarPowerEdge', 'category': 'Off-Grid Power & Energy'},
    {'name': 'LDSreliance', 'focus': 'Off-grid living, DIY solar, prepper', 'url': 'https://www.youtube.com/@LDSreliance', 'category': 'Off-Grid Power & Energy'},
    {'name': 'Off-Grid Garage', 'focus': 'Practical off-grid solar builds', 'url': 'https://www.youtube.com/@OffGridGarage', 'category': 'Off-Grid Power & Energy'},
    # Off-Grid Homesteading
    {'name': 'OFF GRID with DOUG & STACY', 'focus': 'Pioneer-style living, no solar/wind', 'url': 'https://www.youtube.com/@OffGridwithDougandStacy', 'category': 'Off-Grid Homesteading'},
    {'name': 'An American Homestead', 'focus': 'Modern off-grid in the Ozarks', 'url': 'https://www.youtube.com/@AnAmericanHomestead', 'category': 'Off-Grid Homesteading'},
    {'name': 'Guildbrook Farm', 'focus': 'Prepper homesteading, root cellars', 'url': 'https://www.youtube.com/@GuildbrookFarm', 'category': 'Off-Grid Homesteading'},
    {'name': "Kyle's Cabin", 'focus': 'Northern Minnesota off-grid cabin', 'url': 'https://www.youtube.com/@KylesCabin', 'category': 'Off-Grid Homesteading'},
    {'name': 'Markerbuoy', 'focus': '20+ years off-grid, cabin builds, solar', 'url': 'https://www.youtube.com/@Markerbuoy', 'category': 'Off-Grid Homesteading'},
    {'name': 'Better Together Homestead', 'focus': 'Family-first homesteading', 'url': 'https://www.youtube.com/@BetterTogetherHomestead', 'category': 'Off-Grid Homesteading'},
    {'name': 'Homesteady', 'focus': 'How-to homesteading tutorials', 'url': 'https://www.youtube.com/@Homesteady', 'category': 'Off-Grid Homesteading'},
    {'name': 'Living Traditions Homestead', 'focus': 'Living off the land, animals, food preservation', 'url': 'https://www.youtube.com/@LivingTraditionsHomestead', 'category': 'Off-Grid Homesteading'},
    {'name': 'Stoney Ridge Farmer', 'focus': '150-acre farm, gardening, beekeeping', 'url': 'https://www.youtube.com/@StoneyRidgeFarmer', 'category': 'Off-Grid Homesteading'},
    {'name': 'Deep South Homestead', 'focus': 'Mississippi, gardening, animals, cooking', 'url': 'https://www.youtube.com/@DeepSouthHomestead', 'category': 'Off-Grid Homesteading'},
    {'name': 'Martin Johnson Off Grid Living', 'focus': 'Permaculture, composting, solar', 'url': 'https://www.youtube.com/@MartinJohnsonOffGridLiving', 'category': 'Off-Grid Homesteading'},
    {'name': 'Fouch Family Off Grid', 'focus': 'Timber frame house build, homesteading', 'url': 'https://www.youtube.com/@FouchFamilyOffGrid', 'category': 'Off-Grid Homesteading'},
    # Hunting, Trapping & Fishing
    {'name': 'The Hunting Public', 'focus': 'DIY public land deer/turkey (350K+)', 'url': 'https://www.youtube.com/@TheHuntingPublic', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Tim Wells', 'focus': 'Barebow archery, trapping, safaris', 'url': 'https://www.youtube.com/@TimWellsBowHunter', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Hushin', 'focus': 'Hunting + fishing, catch-clean-cook', 'url': 'https://www.youtube.com/@Hushin', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'deermeatfordinner', 'focus': 'Rob Arrington, catch-clean-cook', 'url': 'https://www.youtube.com/@deermeatfordinner', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Survival channel', 'focus': 'Trapping, fishing, hunting, wild edibles (1.6M)', 'url': 'https://www.youtube.com/@Survivalchannel', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'The Wilderness Survival', 'focus': 'Jungle survival, traps, shelters, cooking', 'url': 'https://www.youtube.com/@TheWildernessSurvival', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Field Days', 'focus': 'Solo survival, fishing, spearfishing', 'url': 'https://www.youtube.com/@FieldDays', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'DIY Sportsman', 'focus': 'DIY hunting and fishing', 'url': 'https://www.youtube.com/@DIYSportsman', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Nock On Archery', 'focus': 'Archery skills and bowhunting', 'url': 'https://www.youtube.com/@NockOnArchery', 'category': 'Hunting, Trapping & Fishing'},
    # Emergency Communications
    {'name': 'Radio Prepper', 'focus': 'Emergency radio comms for disasters', 'url': 'https://www.youtube.com/@RadioPrepper', 'category': 'Emergency Communications'},
    {'name': 'Off-Grid Ham', 'focus': 'Portable off-grid ham radio', 'url': 'https://www.youtube.com/@OH8STN', 'category': 'Emergency Communications'},
    {'name': 'The Tech Prepper', 'focus': 'Comms plans, radio equipment', 'url': 'https://www.youtube.com/@TheTechPrepper', 'category': 'Emergency Communications'},
    {'name': 'The Comms Channel', 'focus': 'VHF/UHF, satellites, LoRa/Meshtastic', 'url': 'https://www.youtube.com/@TheCommsChannel', 'category': 'Emergency Communications'},
    {'name': 'Ham Radio Network', 'focus': 'Caleb Nelson, Family Connect System', 'url': 'https://www.youtube.com/@HamRadioNetwork', 'category': 'Emergency Communications'},
    {'name': 'Signals Everywhere', 'focus': 'Radio signals, satellite monitoring', 'url': 'https://www.youtube.com/@SignalsEverywhere', 'category': 'Emergency Communications'},
    {'name': 'Commsprepper', 'focus': 'Best channel for emergency comms', 'url': 'https://www.youtube.com/@Commsprepper', 'category': 'Emergency Communications'},
    # Livestock & Animal Husbandry
    {'name': 'Fresh Eggs Daily', 'focus': 'Natural chicken keeping (largest resource)', 'url': 'https://www.youtube.com/@FreshEggsDaily', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'Delic - A Life of Heritage', 'focus': 'Dairy goats, beekeeping', 'url': 'https://www.youtube.com/@DelicALifeOfHeritage', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'DaddyKirbs Farm', 'focus': 'Permaculture, beekeeping, self-sufficiency', 'url': 'https://www.youtube.com/@DaddyKirbsFarm', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'Twin Oaks Farm', 'focus': 'Quality poultry, meat chickens', 'url': 'https://www.youtube.com/@TwinOaksFarm', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'Richard Perkins', 'focus': 'Permaculture design, agroforestry', 'url': 'https://www.youtube.com/@RidgedaleFarm', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'Acres of Clay Homestead', 'focus': 'Dairy farm, cattle, chickens, ducks', 'url': 'https://www.youtube.com/@AcresOfClayHomestead', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'Dr. Daniel Masaba (Farm Up)', 'focus': 'Multi-animal farm (574K)', 'url': 'https://www.youtube.com/@FarmUp', 'category': 'Livestock & Animal Husbandry'},
    # Shelter Building & Construction
    {'name': 'My Self Reliance (Shawn James)', 'focus': 'Hand-built log cabin, Canadian bush', 'url': 'https://www.youtube.com/@MySelfReliance', 'category': 'Shelter Building & Construction'},
    {'name': 'Wild Wonderful Off-Grid', 'focus': 'A-frame cabin build, off-grid family', 'url': 'https://www.youtube.com/@WildWonderfulOffGrid', 'category': 'Shelter Building & Construction'},
    {'name': 'A Swedish Log Cabin Builder', 'focus': 'Solo hand-built cabin, traditional', 'url': 'https://www.youtube.com/@ASwedishLogCabinBuilder', 'category': 'Shelter Building & Construction'},
    {'name': 'Kris Harbour Natural Building', 'focus': 'Cob, timber, eco-friendly, Wales', 'url': 'https://www.youtube.com/@KrisHarbour', 'category': 'Shelter Building & Construction'},
    {'name': 'Living Big In A Tiny House', 'focus': 'Tiny homes, earthships, yurts, containers', 'url': 'https://www.youtube.com/@LivingBigInATinyHouse', 'category': 'Shelter Building & Construction'},
    {'name': 'Cabinland', 'focus': 'Unique cabin builds in rainforest', 'url': 'https://www.youtube.com/@Cabinland', 'category': 'Shelter Building & Construction'},
    {'name': 'Exploring Alternatives', 'focus': 'Minimalism, off-grid, tiny homes', 'url': 'https://www.youtube.com/@ExploringAlternatives', 'category': 'Shelter Building & Construction'},
    {'name': 'Modern Builds', 'focus': 'Bus conversions, DIY construction (1.7M)', 'url': 'https://www.youtube.com/@ModernBuilds', 'category': 'Shelter Building & Construction'},
    {'name': 'Fritz Tiny Homes', 'focus': 'Custom tiny homes', 'url': 'https://www.youtube.com/@FritzTinyHomes', 'category': 'Shelter Building & Construction'},
    {'name': 'Odd Life Crafting', 'focus': 'Van life, container house, boat restoration', 'url': 'https://www.youtube.com/@OddLifeCrafting', 'category': 'Shelter Building & Construction'},
    # Blacksmithing, Knife Making & Tool Craft
    {'name': 'Alec Steele', 'focus': 'Blacksmithing projects (3M)', 'url': 'https://www.youtube.com/@AlecSteele', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Black Bear Forge', 'focus': 'Practical tools and hardware', 'url': 'https://www.youtube.com/@BlackBearForge', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Walter Sorrells', 'focus': 'Japanese blades, axes, chisels (401K)', 'url': 'https://www.youtube.com/@WalterSorrells', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Jason Knight', 'focus': 'Master bladesmith, tutorials', 'url': 'https://www.youtube.com/@JasonKnight', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Fire Creek Forge', 'focus': 'Forged in Fire champion, tutorials', 'url': 'https://www.youtube.com/@FireCreekForge', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Torbjorn Ahman', 'focus': 'Swedish blacksmith, tools/weapons', 'url': 'https://www.youtube.com/@TorbjornAhman', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Christ Centered Ironworks', 'focus': 'Step-by-step instruction', 'url': 'https://www.youtube.com/@ChristCenteredIronworks', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Simple Little Life', 'focus': 'Knife tutorials, rocket stoves, DIY', 'url': 'https://www.youtube.com/@SimpleLittleLife', 'category': 'Blacksmithing & Tool Craft'},
    {'name': "Cody's Lab", 'focus': 'Chemistry, DIY materials', 'url': 'https://www.youtube.com/@CodysLab', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'How to Make Everything', 'focus': 'Remaking materials from scratch', 'url': 'https://www.youtube.com/@HowToMakeEverything', 'category': 'Blacksmithing & Tool Craft'},
    # Knot Tying, Rope Work & Cordage
    {'name': 'ITS Tactical', 'focus': 'Knot of the Week series', 'url': 'https://www.youtube.com/@ITSTactical', 'category': 'Knot Tying & Cordage'},
    {'name': 'TyingItAllTogether', 'focus': 'Fusion knots, advanced tying', 'url': 'https://www.youtube.com/@TyingItAllTogether', 'category': 'Knot Tying & Cordage'},
    {'name': 'Weavers of Eternity', 'focus': 'Paracord tutorials (995K)', 'url': 'https://www.youtube.com/@WeaversOfEternity', 'category': 'Knot Tying & Cordage'},
    # Wilderness & Outdoor Cooking
    {'name': 'Wilderness Cooking', 'focus': 'Outdoor recipes, survival cooking (4.2M)', 'url': 'https://www.youtube.com/@WildernessCooking', 'category': 'Wilderness Cooking'},
    {'name': 'Men With The Pot', 'focus': 'Open fire and campfire cooking (1.2M)', 'url': 'https://www.youtube.com/@MenWithThePot', 'category': 'Wilderness Cooking'},
    {'name': "Strong's Adventures", 'focus': 'Campfire, Dutch oven, cast iron', 'url': 'https://www.youtube.com/@StrongsAdventures', 'category': 'Wilderness Cooking'},
    {'name': 'Villageria', 'focus': 'Traditional outdoor and village cooking', 'url': 'https://www.youtube.com/@Villageria', 'category': 'Wilderness Cooking'},
    # DIY Survival Goods
    {'name': 'Bramble Berry / Soap Queen', 'focus': 'Soap making tutorials (681K)', 'url': 'https://www.youtube.com/@BrambleBerry', 'category': 'DIY Survival Goods'},
    {'name': 'CandleScience', 'focus': 'Candle making step-by-step', 'url': 'https://www.youtube.com/@CandleScience', 'category': 'DIY Survival Goods'},
    {'name': 'Corter Leather', 'focus': 'Handmade leatherwork, no electricity (677K)', 'url': 'https://www.youtube.com/@CorterLeather', 'category': 'DIY Survival Goods'},
    {'name': 'Essential Soap', 'focus': 'Hot process soap making', 'url': 'https://www.youtube.com/@EssentialSoap', 'category': 'DIY Survival Goods'},
    {'name': 'JH Leather', 'focus': 'Bespoke leatherwork, traditional', 'url': 'https://www.youtube.com/@JHLeather', 'category': 'DIY Survival Goods'},
    {'name': 'Sunshine Soap and Candle Co.', 'focus': 'Candles and cosmetics', 'url': 'https://www.youtube.com/@SunshineSoapAndCandleCo', 'category': 'DIY Survival Goods'},
    {'name': 'Tandy Leather', 'focus': 'Leathercraft tools and tutorials', 'url': 'https://www.youtube.com/@TandyLeather', 'category': 'DIY Survival Goods'},
    # Overland & Bug-Out Vehicles
    {'name': 'ChrisFix', 'focus': 'DIY car repair, step-by-step (10M+)', 'url': 'https://www.youtube.com/@ChrisFix', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'EricTheCarGuy', 'focus': 'Troubleshooting, 800+ repair videos', 'url': 'https://www.youtube.com/@EricTheCarGuy', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'Expedition Overland', 'focus': 'Remote overland adventures, vehicle builds', 'url': 'https://www.youtube.com/@ExpeditionOverland', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'Independence Overland', 'focus': 'Diesel mechanic, overland builds', 'url': 'https://www.youtube.com/@IndependenceOverland', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': "Matt's Off Road Recovery", 'focus': 'Vehicle recovery, getting unstuck', 'url': 'https://www.youtube.com/@MattsOffRoadRecovery', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'Scotty Kilmer', 'focus': 'Mechanic tips, 50+ years (5M+)', 'url': 'https://www.youtube.com/@ScottyKilmer', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'TrailRecon', 'focus': 'How-to guides, tech tips', 'url': 'https://www.youtube.com/@TrailRecon', 'category': 'Overland & Bug-Out Vehicles'},
    # Natural Disaster Preparedness
    {'name': 'Dutchsinse', 'focus': 'Earthquake forecasting (680K)', 'url': 'https://www.youtube.com/@Dutchsinse', 'category': 'Natural Disaster Prep'},
    {'name': 'All Things Wildfire', 'focus': 'Home hardening, insurance, defense', 'url': 'https://www.youtube.com/@AllThingsWildfire', 'category': 'Natural Disaster Prep'},
    {'name': 'Emergency Survival Tips', 'focus': 'Get-home bags, general prep', 'url': 'https://www.youtube.com/@EmergencySurvivalTips', 'category': 'Natural Disaster Prep'},
    {'name': 'Peak Survival', 'focus': 'Bushcraft + emergency prep', 'url': 'https://www.youtube.com/@PeakSurvival', 'category': 'Natural Disaster Prep'},
    # Nuclear, CBRN & WMD Survival
    {"name": "Prepper's Paradigm", 'focus': 'Visual nuclear survival breakdowns', 'url': 'https://www.youtube.com/@PreppersParadigm', 'category': 'Nuclear & CBRN Survival'},
    {'name': 'The Patriot Nurse', 'focus': 'Medical prep, disaster healthcare', 'url': 'https://www.youtube.com/@ThePatriotNurse', 'category': 'Nuclear & CBRN Survival'},
    # Civil Unrest & Societal Collapse
    {'name': 'Frontier Preppers', 'focus': '16 years in Cuba, firsthand tyranny', 'url': 'https://www.youtube.com/@FrontierPreppers', 'category': 'Civil Unrest & Collapse'},
    {'name': 'The Modern Survivalist', 'focus': "Lived through Argentina's collapse", 'url': 'https://www.youtube.com/@TheModernSurvivalist', 'category': 'Civil Unrest & Collapse'},
]

# Category list with counts for UI grouping
CHANNEL_CATEGORIES = sorted(set(c['category'] for c in CHANNEL_CATALOG))
