"""
Curated survival & preparedness content catalog.
210 YouTube channels across 26 categories.
131 tutorial videos + 102 audio training entries.
"""

# ─── YouTube Channel Catalog (210 channels, 26 categories) ─────────────────

CHANNEL_CATALOG = [
    # Wilderness Survival & Bushcraft
    {'name': 'Primitive Technology', 'focus': 'Pure primitive builds, no tools, no dialogue (10M+)', 'url': 'https://www.youtube.com/@primitivetechnology9550', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Survival Lilly', 'focus': 'Shelter, fire, foraging, water purification (2M+)', 'url': 'https://www.youtube.com/@SurvivalLilly', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'My Self Reliance', 'focus': 'Off-grid cabin building, Canadian wilderness', 'url': 'https://www.youtube.com/@MySelfReliance', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'TA Outdoors', 'focus': 'Shelter builds, Viking houses, DIY (2.5M)', 'url': 'https://www.youtube.com/@TAOutdoors', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'MCQBushcraft', 'focus': 'UK bushcraft, fire craft, cinematography', 'url': 'https://www.youtube.com/@MCQBushcraft', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Native Survival', 'focus': 'ALONE finalist, primitive living', 'url': 'https://www.youtube.com/@NativeSurvival', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': "Fowler's Makery and Mischief", 'focus': 'ALONE S3 winner, catch-and-cook, off-grid', 'url': 'https://www.youtube.com/@FowlersMakeryandMischief', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Sigma 3 Survival School', 'focus': 'Comprehensive survival video encyclopedia', 'url': 'https://www.youtube.com/@Sigma3SurvivalSchool', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Frontier Bushcraft', 'focus': 'Shelter building, fire craft instruction', 'url': 'https://www.youtube.com/@FrontierBushcraft', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Bertram - Craft and Wilderness', 'focus': 'Blacksmithing, structures, primitive fishing', 'url': 'https://www.youtube.com/@BertramCraftandWilderness', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Wargeh Bushcraft', 'focus': 'Winter camping, log cabins, off-grid', 'url': 'https://www.youtube.com/@WargehBushcraft', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Smooth Gefixt', 'focus': 'Weekly survival challenges, friction fire', 'url': 'https://www.youtube.com/@SmoothGefixt', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'AlfieAesthetics', 'focus': 'Short, informative bushcraft, foraging, nav', 'url': 'https://www.youtube.com/@AlfieAesthetics', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Survival Russia', 'focus': 'Extreme cold weather, Russian wilderness', 'url': 'https://www.youtube.com/@SurvivalRussia', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Ultimate Survival Tips', 'focus': 'Knives, bows, outdoor survival', 'url': 'https://www.youtube.com/@UltimateSurvivalTips', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'School of Self Reliance', 'focus': 'Comprehensive wilderness self-reliance', 'url': 'https://www.youtube.com/@SchoolOfSelfReliance', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'The Wooded Beardsman', 'focus': 'Canadian bushcraft, cold-weather, gear', 'url': 'https://www.youtube.com/@TheWoodedBeardsman', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Zed Outdoors', 'focus': 'Bushcraft, natural crafts, homesteading', 'url': 'https://www.youtube.com/@ZedOutdoors', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Bushradical', 'focus': '30-day cabin builds, simplicity', 'url': 'https://www.youtube.com/@Bushradical', 'category': 'Wilderness Survival & Bushcraft'},
    # Wild Edible Plants & Foraging
    {'name': 'Learn Your Land', 'focus': 'Mushrooms, plant ID, wild food/medicine', 'url': 'https://www.youtube.com/@LearnYourLand', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Eat The Weeds', 'focus': 'Wild edible identification, recipes', 'url': 'https://www.youtube.com/@EatTheWeeds', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'North Spore', 'focus': 'Mushroom growing, foraging, fungi', 'url': 'https://www.youtube.com/@NorthSpore', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Feral Foraging', 'focus': 'Fundamental foraging skills', 'url': 'https://www.youtube.com/@FeralForaging', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'The3foragers', 'focus': 'Wild edibles, mushroom foraging', 'url': 'https://www.youtube.com/@the3foragers', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Return to Nature', 'focus': 'Foraging, herbalism, mushroom hunting', 'url': 'https://www.youtube.com/@ReturnToNature', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Forage + Feast', 'focus': 'Wild plants, mushrooms, natural foods', 'url': 'https://www.youtube.com/@ForageAndFeast', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'Outdoor Chef Life', 'focus': 'Coastal foraging, seafood', 'url': 'https://www.youtube.com/@OutdoorChefLife', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'EatYourBackyard', 'focus': 'Florida edible wild plants', 'url': 'https://www.youtube.com/@EatYourBackyard', 'category': 'Wild Edible Plants & Foraging'},
    # Medicinal Plants & Wilderness First Aid
    {'name': 'Herbal Academy', 'focus': 'Art & science of plant medicine', 'url': 'https://www.youtube.com/@HerbalAcademy', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'Susun Weed', 'focus': 'Wise Woman tradition, 250+ remedy videos', 'url': 'https://www.youtube.com/@SusunWeed', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'HerbMentor', 'focus': 'Identifying, gathering, preparing wild plants', 'url': 'https://www.youtube.com/@HerbMentor', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'DrBones NurseAmy', 'focus': 'Survival medicine from MD + RN', 'url': 'https://www.youtube.com/@DrBonesNurseAmy', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'PrepMedic', 'focus': 'Flight paramedic, trauma kits, tactical medicine', 'url': 'https://www.youtube.com/@PrepMedic', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'Skinny Medic', 'focus': 'Medical gear, first aid training', 'url': 'https://www.youtube.com/@SkinnyMedic', 'category': 'Medicinal Plants & First Aid'},
    {'name': 'Gray Bearded Green Beret', 'focus': 'First aid, Green Beret survival skills', 'url': 'https://www.youtube.com/@GrayBeardedGreenBeret', 'category': 'Medicinal Plants & First Aid'},
    # Food Preservation & Long-Term Storage
    {'name': 'Homesteading Family', 'focus': 'Canning, freeze-drying, garden preservation', 'url': 'https://www.youtube.com/@HomesteadingFamily', 'category': 'Food Preservation & Storage'},
    {'name': 'Roots and Refuge Farm', 'focus': 'Gardening, farm life, food preservation (600K+)', 'url': 'https://www.youtube.com/@RootsAndRefugeFarm', 'category': 'Food Preservation & Storage'},
    {'name': 'Melissa K. Norris', 'focus': 'Canning, dehydrating, fermenting, salt curing', 'url': 'https://www.youtube.com/@MelissaKNorris', 'category': 'Food Preservation & Storage'},
    {'name': "Becky's Homestead", 'focus': 'Self-sufficient lifestyle, food preservation', 'url': 'https://www.youtube.com/@BeckysHomestead', 'category': 'Food Preservation & Storage'},
    {'name': 'Gubba Homestead', 'focus': 'Garden, preserve, cook, herbal remedies', 'url': 'https://www.youtube.com/@GubbaHomestead', 'category': 'Food Preservation & Storage'},
    {'name': 'Arms Family Homestead', 'focus': 'Large-scale gardening, greenhouse, livestock', 'url': 'https://www.youtube.com/@ArmsFamilyHomestead', 'category': 'Food Preservation & Storage'},
    {'name': 'Justin Rhodes', 'focus': 'Permaculture, pastured livestock, daily vlogs', 'url': 'https://www.youtube.com/@JustinRhodes', 'category': 'Food Preservation & Storage'},
    {'name': 'Growing Your Greens', 'focus': 'Most-watched gardening channel on YouTube', 'url': 'https://www.youtube.com/@GrowingYourGreens', 'category': 'Food Preservation & Storage'},
    {'name': 'Living Web Farms', 'focus': 'Farming, food preservation education', 'url': 'https://www.youtube.com/@LivingWebFarms', 'category': 'Food Preservation & Storage'},
    {'name': 'Self-Sufficient Me', 'focus': 'Food production, garden, self-sufficiency', 'url': 'https://www.youtube.com/@SelfSufficientMe', 'category': 'Food Preservation & Storage'},
    # Prepper & Emergency Preparedness
    {'name': 'Canadian Prepper', 'focus': 'Gear reviews, current events, DIY projects (2M+)', 'url': 'https://www.youtube.com/@CanadianPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'City Prepping', 'focus': 'Urban/suburban survival, high production (1M+)', 'url': 'https://www.youtube.com/@CityPrepping', 'category': 'Prepper & Emergency Prep'},
    {'name': 'The Urban Prepper', 'focus': 'City survival, compact kits, family-friendly (500K+)', 'url': 'https://www.youtube.com/@TheUrbanPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Sensible Prepper', 'focus': 'Gear reviews, firearms, preparedness (1M+)', 'url': 'https://www.youtube.com/@SensiblePrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'The Provident Prepper', 'focus': 'Family preparedness, food/water storage (400K+)', 'url': 'https://www.youtube.com/@TheProvidentPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'SouthernPrepper1', 'focus': 'Homestead prepping, gardening, livestock (500K+)', 'url': 'https://www.youtube.com/@SouthernPrepper1', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Magic Prepper', 'focus': 'Gear deep-dives, post-collapse philosophy (300K+)', 'url': 'https://www.youtube.com/@MagicPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Bear Independent', 'focus': 'Food storage, self-defense, no-nonsense (300K+)', 'url': 'https://www.youtube.com/@BearIndependent', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Step One Survival', 'focus': 'Beginner-friendly, bug-out bags, basics (170K+)', 'url': 'https://www.youtube.com/@StepOneSurvival', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Survival Dispatch', 'focus': 'Expert collective, bite-sized tutorials (200K+)', 'url': 'https://www.youtube.com/@SurvivalDispatch', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Full Spectrum Survival', 'focus': 'Alert updates, crisis information (300K+)', 'url': 'https://www.youtube.com/@FullSpectrumSurvival', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Funky Prepper', 'focus': 'Former British Infantry, bug-out preps (100K+)', 'url': 'https://www.youtube.com/@FunkyPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Last Line of Defense', 'focus': 'Gear reviews, survivalist focus (100K+)', 'url': 'https://www.youtube.com/@LastLineOfDefense', 'category': 'Prepper & Emergency Prep'},
    # Self-Defense & Security
    {'name': 'Active Self Protection', 'focus': 'Real-world self-defense analysis', 'url': 'https://www.youtube.com/@ActiveSelfProtection', 'category': 'Self-Defense & Security'},
    {'name': 'Warrior Poet Society', 'focus': 'Former Ranger, tactics + philosophy', 'url': 'https://www.youtube.com/@WarriorPoetSociety', 'category': 'Self-Defense & Security'},
    {'name': 'Hickok45', 'focus': 'Firearms safety, reviews, shooting', 'url': 'https://www.youtube.com/@hickok45', 'category': 'Self-Defense & Security'},
    {'name': 'Black Scout Survival', 'focus': 'Tactical + wilderness, lock picking', 'url': 'https://www.youtube.com/@BlackScoutSurvival', 'category': 'Self-Defense & Security'},
    {'name': 'Nutnfancy', 'focus': 'Gear reviews, tactical philosophy', 'url': 'https://www.youtube.com/@nutnfancy', 'category': 'Self-Defense & Security'},
    {'name': 'FieldCraft Survival', 'focus': 'Tactical skills, wet-weather fire', 'url': 'https://www.youtube.com/@FieldCraftSurvival', 'category': 'Self-Defense & Security'},
    {'name': 'Survival Gear', 'focus': 'Tactical & survival gear reviews (782K)', 'url': 'https://www.youtube.com/@SurvivalGear', 'category': 'Self-Defense & Security'},
    {'name': 'Garand Thumb', 'focus': 'Military and civilian firearm testing, gear selection, tactics — honest no-BS reviews (2M+)', 'url': 'https://www.youtube.com/@GarandThumb', 'category': 'Self-Defense & Security'},
    {'name': 'Tactical Rifleman', 'focus': 'Former Special Forces soldiers — real-world tactics, CQB, combat shooting, patrol techniques', 'url': 'https://www.youtube.com/@TacticalRifleman', 'category': 'Self-Defense & Security'},
    # Off-Grid Power & Energy
    {'name': 'DIY Solar Power (Will Prowse)', 'focus': 'DIY solar builds, gear reviews (1M+)', 'url': 'https://www.youtube.com/@WillProwse', 'category': 'Off-Grid Power & Energy'},
    {'name': 'Engineer775', 'focus': 'Off-grid systems, water, solar, heating', 'url': 'https://www.youtube.com/@Engineer775', 'category': 'Off-Grid Power & Energy'},
    {'name': 'Solar Power Edge', 'focus': 'Creative solar, high-tech survival', 'url': 'https://www.youtube.com/@SolarPowerEdge', 'category': 'Off-Grid Power & Energy'},
    {'name': 'LDSreliance', 'focus': 'Off-grid living, DIY solar, prepper', 'url': 'https://www.youtube.com/@LDSreliance', 'category': 'Off-Grid Power & Energy'},
    {'name': 'Off-Grid Garage', 'focus': 'Practical off-grid solar builds', 'url': 'https://www.youtube.com/@OffGridGarage', 'category': 'Off-Grid Power & Energy'},
    # Off-Grid Homesteading
    {'name': 'An American Homestead', 'focus': 'Modern off-grid in the Ozarks', 'url': 'https://www.youtube.com/@AnAmericanHomestead', 'category': 'Off-Grid Homesteading'},
    {'name': 'Guildbrook Farm', 'focus': 'Prepper homesteading, root cellars', 'url': 'https://www.youtube.com/@GuildbrookFarm', 'category': 'Off-Grid Homesteading'},
    {'name': "Kyle's Cabin", 'focus': 'Northern Minnesota off-grid cabin', 'url': 'https://www.youtube.com/@KylesCabin', 'category': 'Off-Grid Homesteading'},
    {'name': 'Markerbuoy', 'focus': '20+ years off-grid, cabin builds, solar', 'url': 'https://www.youtube.com/@Markerbuoy', 'category': 'Off-Grid Homesteading'},
    {'name': 'Living Traditions Homestead', 'focus': 'Living off the land, animals, food preservation', 'url': 'https://www.youtube.com/@LivingTraditionsHomestead', 'category': 'Off-Grid Homesteading'},
    {'name': 'Stoney Ridge Farmer', 'focus': '150-acre farm, gardening, beekeeping', 'url': 'https://www.youtube.com/@StoneyRidgeFarmer', 'category': 'Off-Grid Homesteading'},
    {'name': 'Deep South Homestead', 'focus': 'Mississippi, gardening, animals, cooking', 'url': 'https://www.youtube.com/@DeepSouthHomestead', 'category': 'Off-Grid Homesteading'},
    {'name': 'Martin Johnson Off Grid Living', 'focus': 'Permaculture, composting, solar', 'url': 'https://www.youtube.com/@MartinJohnsonOffGridLiving', 'category': 'Off-Grid Homesteading'},
    # Hunting, Trapping & Fishing
    {'name': 'The Hunting Public', 'focus': 'DIY public land deer/turkey (350K+)', 'url': 'https://www.youtube.com/@TheHuntingPublic', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Tim Wells', 'focus': 'Barebow archery, trapping, safaris', 'url': 'https://www.youtube.com/@TimWellsBowHunter', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'deermeatfordinner', 'focus': 'Rob Arrington, catch-clean-cook', 'url': 'https://www.youtube.com/@deermeatfordinner', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Survival channel', 'focus': 'Trapping, fishing, hunting, wild edibles (1.6M)', 'url': 'https://www.youtube.com/@Survivalchannel', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Field Days', 'focus': 'Solo survival, fishing, spearfishing', 'url': 'https://www.youtube.com/@FieldDays', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'DIY Sportsman', 'focus': 'DIY hunting and fishing', 'url': 'https://www.youtube.com/@DIYSportsman', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'Nock On Archery', 'focus': 'Archery skills and bowhunting', 'url': 'https://www.youtube.com/@NockOnArchery', 'category': 'Hunting, Trapping & Fishing'},
    # Emergency Communications
    {'name': 'Radio Prepper', 'focus': 'Emergency radio comms for disasters', 'url': 'https://www.youtube.com/@RadioPrepper', 'category': 'Emergency Communications'},
    {'name': 'Off-Grid Ham', 'focus': 'Portable off-grid ham radio', 'url': 'https://www.youtube.com/@OH8STN', 'category': 'Emergency Communications'},
    {'name': 'The Tech Prepper', 'focus': 'Comms plans, radio equipment', 'url': 'https://www.youtube.com/@TheTechPrepper', 'category': 'Emergency Communications'},
    {'name': 'Signals Everywhere', 'focus': 'Radio signals, satellite monitoring', 'url': 'https://www.youtube.com/@SignalsEverywhere', 'category': 'Emergency Communications'},
    {'name': 'Commsprepper', 'focus': 'Best channel for emergency comms', 'url': 'https://www.youtube.com/@Commsprepper', 'category': 'Emergency Communications'},
    # Livestock & Animal Husbandry
    {'name': 'Fresh Eggs Daily', 'focus': 'Natural chicken keeping (largest resource)', 'url': 'https://www.youtube.com/@FreshEggsDaily', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'Twin Oaks Farm', 'focus': 'Quality poultry, meat chickens', 'url': 'https://www.youtube.com/@TwinOaksFarm', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'Acres of Clay Homestead', 'focus': 'Dairy farm, cattle, chickens, ducks', 'url': 'https://www.youtube.com/@AcresOfClayHomestead', 'category': 'Livestock & Animal Husbandry'},
    {'name': 'Dr. Daniel Masaba (Farm Up)', 'focus': 'Multi-animal farm (574K)', 'url': 'https://www.youtube.com/@FarmUp', 'category': 'Livestock & Animal Husbandry'},
    # Shelter Building & Construction
    {'name': 'My Self Reliance (Shawn James)', 'focus': 'Hand-built log cabin, Canadian bush', 'url': 'https://www.youtube.com/@MySelfReliance', 'category': 'Shelter Building & Construction'},
    {'name': 'Wild Wonderful Off-Grid', 'focus': 'A-frame cabin build, off-grid family', 'url': 'https://www.youtube.com/@WildWonderfulOffGrid', 'category': 'Shelter Building & Construction'},
    {'name': 'Kris Harbour Natural Building', 'focus': 'Cob, timber, eco-friendly, Wales', 'url': 'https://www.youtube.com/@KrisHarbour', 'category': 'Shelter Building & Construction'},
    {'name': 'Living Big In A Tiny House', 'focus': 'Tiny homes, earthships, yurts, containers', 'url': 'https://www.youtube.com/@LivingBigInATinyHouse', 'category': 'Shelter Building & Construction'},
    {'name': 'Cabinland', 'focus': 'Unique cabin builds in rainforest', 'url': 'https://www.youtube.com/@Cabinland', 'category': 'Shelter Building & Construction'},
    {'name': 'Exploring Alternatives', 'focus': 'Minimalism, off-grid, tiny homes', 'url': 'https://www.youtube.com/@ExploringAlternatives', 'category': 'Shelter Building & Construction'},
    {'name': 'Modern Builds', 'focus': 'Bus conversions, DIY construction (1.7M)', 'url': 'https://www.youtube.com/@ModernBuilds', 'category': 'Shelter Building & Construction'},
    {'name': 'Odd Life Crafting', 'focus': 'Van life, container house, boat restoration', 'url': 'https://www.youtube.com/@OddLifeCrafting', 'category': 'Shelter Building & Construction'},
    # Blacksmithing, Knife Making & Tool Craft
    {'name': 'Alec Steele', 'focus': 'Blacksmithing projects (3M)', 'url': 'https://www.youtube.com/@AlecSteele', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Black Bear Forge', 'focus': 'Practical tools and hardware', 'url': 'https://www.youtube.com/@BlackBearForge', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Jason Knight', 'focus': 'Master bladesmith, tutorials', 'url': 'https://www.youtube.com/@JasonKnight', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Fire Creek Forge', 'focus': 'Forged in Fire champion, tutorials', 'url': 'https://www.youtube.com/@FireCreekForge', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Torbjorn Ahman', 'focus': 'Swedish blacksmith, tools/weapons', 'url': 'https://www.youtube.com/@TorbjornAhman', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Christ Centered Ironworks', 'focus': 'Step-by-step instruction', 'url': 'https://www.youtube.com/@ChristCenteredIronworks', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Simple Little Life', 'focus': 'Knife tutorials, rocket stoves, DIY', 'url': 'https://www.youtube.com/@SimpleLittleLife', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'How to Make Everything', 'focus': 'Remaking materials from scratch', 'url': 'https://www.youtube.com/@HowToMakeEverything', 'category': 'Blacksmithing & Tool Craft'},
    # Knot Tying, Rope Work & Cordage
    {'name': 'ITS Tactical', 'focus': 'Knot of the Week series', 'url': 'https://www.youtube.com/@ITSTactical', 'category': 'Knot Tying & Cordage'},
    {'name': 'TyingItAllTogether', 'focus': 'Fusion knots, advanced tying', 'url': 'https://www.youtube.com/@TyingItAllTogether', 'category': 'Knot Tying & Cordage'},
    {'name': 'Animated Knots by Grog', 'focus': "World's most comprehensive knot reference — 200+ knots with step-by-step animation, boating/sailing/climbing/survival (1M+)", 'url': 'https://www.youtube.com/@AnimatedKnotsbyGrog', 'category': 'Knot Tying & Cordage'},
    # Wilderness & Outdoor Cooking
    {'name': 'Wilderness Cooking', 'focus': 'Outdoor recipes, survival cooking (4.2M)', 'url': 'https://www.youtube.com/@WildernessCooking', 'category': 'Wilderness Cooking'},
    {'name': 'Men With The Pot', 'focus': 'Open fire and campfire cooking (1.2M)', 'url': 'https://www.youtube.com/@MenWithThePot', 'category': 'Wilderness Cooking'},
    {'name': "Strong's Adventures", 'focus': 'Campfire, Dutch oven, cast iron', 'url': 'https://www.youtube.com/@StrongsAdventures', 'category': 'Wilderness Cooking'},
    {'name': 'Villageria', 'focus': 'Traditional outdoor and village cooking', 'url': 'https://www.youtube.com/@Villageria', 'category': 'Wilderness Cooking'},
    # DIY Survival Goods
    {'name': 'Bramble Berry / Soap Queen', 'focus': 'Soap making tutorials (681K)', 'url': 'https://www.youtube.com/@BrambleBerry', 'category': 'DIY Survival Goods'},
    {'name': 'CandleScience', 'focus': 'Candle making step-by-step', 'url': 'https://www.youtube.com/@CandleScience', 'category': 'DIY Survival Goods'},
    {'name': 'Essential Soap', 'focus': 'Hot process soap making', 'url': 'https://www.youtube.com/@EssentialSoap', 'category': 'DIY Survival Goods'},
    {'name': 'JH Leather', 'focus': 'Bespoke leatherwork, traditional', 'url': 'https://www.youtube.com/@JHLeather', 'category': 'DIY Survival Goods'},
    # Overland & Bug-Out Vehicles
    {'name': 'ChrisFix', 'focus': 'DIY car repair, step-by-step (10M+)', 'url': 'https://www.youtube.com/@ChrisFix', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'EricTheCarGuy', 'focus': 'Troubleshooting, 800+ repair videos', 'url': 'https://www.youtube.com/@EricTheCarGuy', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'Expedition Overland', 'focus': 'Remote overland adventures, vehicle builds', 'url': 'https://www.youtube.com/@ExpeditionOverland', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'Independence Overland', 'focus': 'Diesel mechanic, overland builds', 'url': 'https://www.youtube.com/@IndependenceOverland', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': "Matt's Off Road Recovery", 'focus': 'Vehicle recovery, getting unstuck', 'url': 'https://www.youtube.com/@MattsOffRoadRecovery', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'Scotty Kilmer', 'focus': 'Mechanic tips, 50+ years (5M+)', 'url': 'https://www.youtube.com/@ScottyKilmer', 'category': 'Overland & Bug-Out Vehicles'},
    {'name': 'TrailRecon', 'focus': 'How-to guides, tech tips', 'url': 'https://www.youtube.com/@TrailRecon', 'category': 'Overland & Bug-Out Vehicles'},
    # Natural Disaster Preparedness
    {'name': 'Dutchsinse', 'focus': 'Earthquake forecasting (680K)', 'url': 'https://www.youtube.com/@Dutchsinse', 'category': 'Natural Disaster Prep'},
    {'name': 'All Things Wildfire', 'focus': 'Home hardening, insurance, defense', 'url': 'https://www.youtube.com/@AllThingsWildfire', 'category': 'Natural Disaster Prep'},
    {'name': 'Emergency Survival Tips', 'focus': 'Get-home bags, general prep', 'url': 'https://www.youtube.com/@EmergencySurvivalTips', 'category': 'Natural Disaster Prep'},
    {'name': 'Peak Survival', 'focus': 'Bushcraft + emergency prep', 'url': 'https://www.youtube.com/@PeakSurvival', 'category': 'Natural Disaster Prep'},
    # Nuclear, CBRN & WMD Survival
    {"name": "Prepper's Paradigm", 'focus': 'Visual nuclear survival breakdowns', 'url': 'https://www.youtube.com/@PreppersParadigm', 'category': 'Nuclear & CBRN Survival'},
    {'name': 'The Patriot Nurse', 'focus': 'Medical prep, disaster healthcare', 'url': 'https://www.youtube.com/@ThePatriotNurse', 'category': 'Nuclear & CBRN Survival'},
    # Civil Unrest & Societal Collapse
    {'name': 'Frontier Preppers', 'focus': '16 years in Cuba, firsthand tyranny', 'url': 'https://www.youtube.com/@FrontierPreppers', 'category': 'Civil Unrest & Collapse'},
    {'name': 'The Modern Survivalist', 'focus': "Lived through Argentina's collapse", 'url': 'https://www.youtube.com/@TheModernSurvivalist', 'category': 'Civil Unrest & Collapse'},
    {'name': 'Selco SHTF School', 'focus': 'Survived 1-year siege in Balkan War — real collapse skills, not theory', 'url': 'https://www.youtube.com/@selcoSHTF', 'category': 'Civil Unrest & Collapse'},
    {'name': 'Peak Prosperity (Chris Martenson)', 'focus': 'PhD biologist — economic collapse, energy depletion, systemic risk, resilience planning with data-driven analysis', 'url': 'https://www.youtube.com/@PeakProsperity', 'category': 'Civil Unrest & Collapse'},
    # Additional Wilderness Survival & Bushcraft
    {'name': 'Corporals Corner', 'focus': 'Military-style bushcraft and survival, detailed knife/gear reviews (800K+)', 'url': 'https://www.youtube.com/@CorporalsCorner', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Reality Survival & Prepping', 'focus': "Dave Canterbury's Pathfinder School — fire, water, shelter, trapping", 'url': 'https://www.youtube.com/@RealitySurvival', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Les Stroud (Survivorman)', 'focus': 'Real solo survival — no crew, no safety net (Survivorman)', 'url': 'https://www.youtube.com/@LesStroud', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Brave Wilderness', 'focus': 'Wildlife education — bites, stings, venomous creatures, nature safety (18M+)', 'url': 'https://www.youtube.com/@BraveWilderness', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Coalcracker Bushcraft', 'focus': 'Appalachian woodland survival, knives, fire craft, traditional crafts', 'url': 'https://www.youtube.com/@CoalcrackerBushcraft', 'category': 'Wilderness Survival & Bushcraft'},
    {'name': 'Creek Stewart', 'focus': 'EJ Snyder and Creek Stewart survival school, TV host Fat Guys in the Woods', 'url': 'https://www.youtube.com/@CreekStewart', 'category': 'Wilderness Survival & Bushcraft'},
    # Additional Wild Edible Plants & Foraging
    {'name': 'Foraging Texas', 'focus': 'Texas and Southwest edible wild plants — detailed regional ID guides', 'url': 'https://www.youtube.com/@ForagingTexas', 'category': 'Wild Edible Plants & Foraging'},
    {'name': 'WildFoodUK', 'focus': 'UK and European foraging — wild plants, mushrooms, seasonal harvest', 'url': 'https://www.youtube.com/@WildFoodUK', 'category': 'Wild Edible Plants & Foraging'},
    # Additional Food Preservation & Storage
    {"name": "Mary's Nest", 'focus': 'Traditional food skills — bone broth, fermenting, sourdough, pantry storage (800K+)', 'url': "https://www.youtube.com/@MarysNest", 'category': 'Food Preservation & Storage'},
    # Additional Prepper & Emergency Prep
    {'name': 'The Angry Prepper', 'focus': 'NYC urban prepper — tactical analysis, firearms, no-nonsense content (250K+)', 'url': 'https://www.youtube.com/@TheAngryPrepper', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Tin Hat Ranch', 'focus': 'Tech-savvy preparedness — comms, solar, privacy, Faraday cages (300K+)', 'url': 'https://www.youtube.com/@TinHatRanch', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Practical Preppers', 'focus': 'Scott Hunt — resilient EMP/grid-down homesteads, National Geographic featured', 'url': 'https://www.youtube.com/@PracticalPreppers', 'category': 'Prepper & Emergency Prep'},
    {'name': 'The Prepared', 'focus': 'Evidence-based preparedness — gear reviews, bug-out bags, scenario planning', 'url': 'https://www.youtube.com/@theprepared', 'category': 'Prepper & Emergency Prep'},
    # Additional Emergency Communications
    {'name': 'Ham Radio Crash Course', 'focus': 'Best HAM radio exam prep — Technician through Extra class (600K+)', 'url': 'https://www.youtube.com/@HamRadioCrashCourse', 'category': 'Emergency Communications'},
    {'name': 'Ham Radio 2.0', 'focus': 'Amateur radio operations, EMCOMM, APRS, digital modes', 'url': 'https://www.youtube.com/@HamRadio2', 'category': 'Emergency Communications'},
    {'name': 'K8MRD Radio Activities', 'focus': 'Emergency communications, ARES/RACES, portable operations', 'url': 'https://www.youtube.com/@K8MRDRadioActivities', 'category': 'Emergency Communications'},
    {'name': 'Andreas Spiess', 'focus': 'LoRa/LoRaWAN mesh networking, long-range IoT radio for off-grid sensor networks (800K+)', 'url': 'https://www.youtube.com/@AndreasSpiess', 'category': 'Emergency Communications'},
    {'name': 'KM4ACK (Jason Oleham)', 'focus': 'Raspberry Pi for ham radio — JS8Call, Winlink, digital modes on low power (200K+)', 'url': 'https://www.youtube.com/@KM4ACK', 'category': 'Emergency Communications'},
    {'name': 'OH8STN Julian OH8STN', 'focus': 'Off-grid solar-powered digital HF radio — JS8Call, Winlink from wilderness', 'url': 'https://www.youtube.com/@OH8STN', 'category': 'Emergency Communications'},
    # Additional Off-Grid Power & Energy
    {'name': 'Undecided with Matt Ferrell', 'focus': 'Renewable energy tech — solar, batteries, EVs reviewed objectively (1.5M+)', 'url': 'https://www.youtube.com/@UndecidedMF', 'category': 'Off-Grid Power & Energy'},
    {'name': 'Hobotech', 'focus': 'Deep-dive power station/solar generator reviews and battery testing', 'url': 'https://www.youtube.com/@hobotech', 'category': 'Off-Grid Power & Energy'},
    # Additional Natural Disaster Prep
    {'name': 'USGS Hazards', 'focus': 'Official USGS — real-time earthquake, volcano, landslide, flood monitoring', 'url': 'https://www.youtube.com/@USGSvideo', 'category': 'Natural Disaster Prep'},
    {'name': 'Storm Highway', 'focus': 'Severe weather photography, lightning, tornadoes, storm chasing safety', 'url': 'https://www.youtube.com/@stormhighway', 'category': 'Natural Disaster Prep'},
    # Additional Nuclear & CBRN Survival
    {'name': 'Nuclear Vault', 'focus': 'Archive of US government civil defense and nuclear preparedness films', 'url': 'https://www.youtube.com/@NuclearVault', 'category': 'Nuclear & CBRN Survival'},
    # Additional Hunting, Trapping & Fishing
    {'name': 'Shawn Woods', 'focus': 'Primitive trapping, flintknapping, ancient hunting technologies (600K+)', 'url': 'https://www.youtube.com/@ShawnWoods1', 'category': 'Hunting, Trapping & Fishing'},
    {'name': 'MeatEater', 'focus': 'Steven Rinella — ethical hunting, butchering, wild game cookery (1M+)', 'url': 'https://www.youtube.com/@MeatEaterTV', 'category': 'Hunting, Trapping & Fishing'},
    # Additional Blacksmithing & Tool Craft
    {'name': 'Open Source Ecology', 'focus': 'Global Village Construction Set — 50 industrial machines buildable from scratch', 'url': 'https://www.youtube.com/@OpenSourceEcology', 'category': 'Blacksmithing & Tool Craft'},
    {'name': 'Clickspring', 'focus': 'Precision machining and recreation of ancient tools and mechanisms', 'url': 'https://www.youtube.com/@Clickspring', 'category': 'Blacksmithing & Tool Craft'},
    # Additional DIY Survival Goods
    {'name': 'NileRed', 'focus': 'Chemistry from raw materials — synthesizing compounds, extracting elements', 'url': 'https://www.youtube.com/@NileRed', 'category': 'DIY Survival Goods'},
    # Additional Livestock & Animal Husbandry
    {'name': 'Becky Goats', 'focus': 'Dairy goat keeping, kidding, milk production, herd health', 'url': 'https://www.youtube.com/@BeckyGoats', 'category': 'Livestock & Animal Husbandry'},
    # NEW CATEGORY: Permaculture & Regenerative Agriculture
    {'name': 'Epic Gardening', 'focus': 'Modern intensive food growing — raised beds, hydroponics, seed saving (3M+)', 'url': 'https://www.youtube.com/@EpicGardening', 'category': 'Permaculture & Regenerative Agriculture'},
    {'name': 'Geoff Lawton Online', 'focus': "World's leading permaculture educator — food forests, water harvesting", 'url': 'https://www.youtube.com/@GeoffLawtonOnline', 'category': 'Permaculture & Regenerative Agriculture'},
    {'name': 'Paul Wheaton (Permies)', 'focus': 'Permaculture, natural building, rocket mass heaters (permies.com founder)', 'url': 'https://www.youtube.com/@paulwheaton1', 'category': 'Permaculture & Regenerative Agriculture'},
    {'name': 'Happen Films', 'focus': 'Permaculture documentaries — food forests, regenerative farms worldwide (1M+)', 'url': 'https://www.youtube.com/@happenfilms', 'category': 'Permaculture & Regenerative Agriculture'},
    {'name': 'Edible Acres', 'focus': 'Food forest establishment, perennial vegetables, resilient growing systems', 'url': 'https://www.youtube.com/@EdibleAcres', 'category': 'Permaculture & Regenerative Agriculture'},
    {'name': 'Practical Engineering', 'focus': 'Civil and water engineering explained — dams, filtration, infrastructure (5M+)', 'url': 'https://www.youtube.com/@PracticalEngineeringChannel', 'category': 'Permaculture & Regenerative Agriculture'},
    {'name': 'The Urban Farmer (Curtis Stone)', 'focus': 'High-density market gardening — quarter-acre food production, permanent bed systems, direct sales (600K+)', 'url': 'https://www.youtube.com/@theurbanfarmer', 'category': 'Permaculture & Regenerative Agriculture'},
    # NEW CATEGORY: Traditional & Primitive Skills
    {'name': 'Townsends', 'focus': '18th century cooking, crafts, and daily life — historical self-sufficiency (2M+)', 'url': 'https://www.youtube.com/@Townsends', 'category': 'Traditional & Primitive Skills'},
    {'name': 'Far North Bushcraft And Survival', 'focus': 'Sub-arctic traditional skills, spruce root baskets, hide tanning', 'url': 'https://www.youtube.com/@FarNorthBushcraftAndSurvival', 'category': 'Traditional & Primitive Skills'},
    {'name': 'Stone Age Man', 'focus': 'Primitive stone tools, flintknapping, bow drill fire from stone-age materials', 'url': 'https://www.youtube.com/@StoneAgeMan', 'category': 'Traditional & Primitive Skills'},
    {'name': 'Lynx Vilden', 'focus': 'Stone-age living — hide tanning, primitive fire, wild plant use', 'url': 'https://www.youtube.com/@LynxVilden', 'category': 'Traditional & Primitive Skills'},
    {'name': 'Forgotten Weapons', 'focus': 'Ian McCollum — history and mechanics of rare/obsolete firearms — understand every weapon you might encounter (3M+)', 'url': 'https://www.youtube.com/@ForgottenWeapons', 'category': 'Traditional & Primitive Skills'},
    {'name': 'Jocko Podcast', 'focus': 'Navy SEAL leadership, discipline, combat mindset, resilience under pressure (1.5M+)', 'url': 'https://www.youtube.com/@JockoPodcast', 'category': 'Prepper & Emergency Prep'},
    {'name': 'Mark Divine (SEALFIT)', 'focus': 'Unbeatable Mind — combat veteran mental toughness, tactical breathing, stress inoculation', 'url': 'https://www.youtube.com/@MarkDivine', 'category': 'Prepper & Emergency Prep'},
    # NEW CATEGORY: Meteorology & Weather
    {'name': 'Ryan Hall Y\'all', 'focus': 'Storm chasing and severe weather education — tornado/hurricane forecasting explained for the public (1.2M+)', 'url': 'https://www.youtube.com/@RyanHallYall', 'category': 'Meteorology & Weather'},
    {'name': 'Tropical Tidbits', 'focus': 'Best hurricane and severe weather model analysis — spaghetti plots, ensemble forecasting explained for laypeople (400K+)', 'url': 'https://www.youtube.com/@tropicaltidbits', 'category': 'Meteorology & Weather'},
    {'name': 'The COMET Program', 'focus': 'UCAR/NOAA official meteorology training — atmospheric dynamics, radar interpretation, forecasting theory (100K+)', 'url': 'https://www.youtube.com/@MetEd_COMET', 'category': 'Meteorology & Weather'},
    {'name': 'NWS Headquarters', 'focus': 'Official NOAA National Weather Service — severe weather warnings, preparedness, weather safety education', 'url': 'https://www.youtube.com/@NWSHeadquarters', 'category': 'Meteorology & Weather'},
    {'name': 'Cliff Mass Weather', 'focus': 'Pacific NW weather expert — atmospheric rivers, orographic rain, wildfire weather, regional climate patterns', 'url': 'https://www.youtube.com/@CliffMassWeather', 'category': 'Meteorology & Weather'},
    {'name': 'EFactor Weather', 'focus': 'Independent severe weather forecasting — Midwest tornadoes, derechos, winter storms with model analysis', 'url': 'https://www.youtube.com/@EFactorWeather', 'category': 'Meteorology & Weather'},
    {'name': 'WeatherNation', 'focus': 'Live severe weather coverage — tornadoes, hurricanes, blizzards without filler or hype (500K+)', 'url': 'https://www.youtube.com/@WeatherNation', 'category': 'Meteorology & Weather'},
    {'name': 'Reed Timmer', 'focus': 'Extreme meteorologist — intercepts F5 tornadoes, explains atmospheric science of severe weather (500K+)', 'url': 'https://www.youtube.com/@ReedTimmer', 'category': 'Meteorology & Weather'},
    {'name': 'Meteo 365', 'focus': 'Long-range forecast discussions, El Niño/La Niña impacts, climate pattern analysis for seasonal planning', 'url': 'https://www.youtube.com/@Meteo365', 'category': 'Meteorology & Weather'},
    {'name': 'iWeatherNet', 'focus': 'Regional US weather forecasting — model interpretation, winter storm coverage, severe weather outlooks', 'url': 'https://www.youtube.com/@iWeatherNet', 'category': 'Meteorology & Weather'},
    # NEW CATEGORY: Geospatial & Mapping
    {'name': 'USGS (US Geological Survey)', 'focus': 'Official USGS — topographic maps, earthquake/volcano hazards, water resources, geologic mapping (300K+)', 'url': 'https://www.youtube.com/@USGSgov', 'category': 'Geospatial & Mapping'},
    {'name': 'GIS Geography', 'focus': 'GIS tutorials — QGIS, cartography, remote sensing, spatial analysis for creating offline maps (200K+)', 'url': 'https://www.youtube.com/@GISGeography', 'category': 'Geospatial & Mapping'},
    {'name': 'NOAA Satellites and Information', 'focus': 'Official NOAA — satellite imagery, ocean monitoring, remote sensing, climate observation systems', 'url': 'https://www.youtube.com/@NOAASatellites', 'category': 'Geospatial & Mapping'},
    {'name': 'geodesign', 'focus': 'QGIS and open-source GIS tutorials — processing elevation data, creating offline maps, terrain analysis', 'url': 'https://www.youtube.com/@geodesignchannel', 'category': 'Geospatial & Mapping'},
    {'name': 'MapScaping', 'focus': 'Geospatial industry interviews — satellite data, terrain modeling, open data sources for offline navigation', 'url': 'https://www.youtube.com/@MapScaping', 'category': 'Geospatial & Mapping'},
    {'name': 'OpenStreetMap (OSMF)', 'focus': 'Official OSM Foundation — how to download, use, and contribute to the world\'s best offline map dataset', 'url': 'https://www.youtube.com/@openstreetmapfoundation', 'category': 'Geospatial & Mapping'},
    # NEW CATEGORY: Water & Sanitation
    {'name': 'Practical Engineering', 'focus': 'Civil engineer Grady Hillhouse — water treatment, wells, sewage, infrastructure explained clearly (4M+)', 'url': 'https://www.youtube.com/@PracticalEngineeringChannel', 'category': 'Water & Sanitation'},
    {'name': 'CAWST Centre for Affordable Water', 'focus': 'WHO-endorsed water treatment for developing contexts — biosand filters, SODIS, ceramic filters, chlorination', 'url': 'https://www.youtube.com/@CAWSTorg', 'category': 'Water & Sanitation'},
    {'name': 'Open Source Ecology', 'focus': 'GVCS civilization toolkit — tractor, well drill, CEB press, sawmill — reproducible machines for off-grid living (300K+)', 'url': 'https://www.youtube.com/@OpenSourceEcology', 'category': 'Water & Sanitation'},
    {'name': 'Rain Bird Academy', 'focus': 'Irrigation system design and installation — drip, sprinkler, grey water reuse for food production', 'url': 'https://www.youtube.com/@RainBirdCorp', 'category': 'Water & Sanitation'},
    {'name': 'Benson Filtration', 'focus': 'Residential well water treatment — iron removal, softeners, whole-house filters, reverse osmosis explained', 'url': 'https://www.youtube.com/@BensonFiltration', 'category': 'Water & Sanitation'},
    # NEW CATEGORY: Mental Resilience & Leadership
    {'name': 'Extreme Ownership (Jocko Willink)', 'focus': 'Navy SEAL leadership — discipline, decentralized command, stress decision-making (2.5M+)', 'url': 'https://www.youtube.com/@jockowillink', 'category': 'Mental Resilience & Leadership'},
    {'name': 'Andy Stumpf', 'focus': 'Former SEAL Team 6 — mindset under extreme stress, high-performance habits, crisis management', 'url': 'https://www.youtube.com/@AndyStumpf', 'category': 'Mental Resilience & Leadership'},
    {'name': 'The Psychological Health Center', 'focus': 'FEMA psychological first aid training — crisis counseling, trauma-informed care, community resilience after disasters', 'url': 'https://www.youtube.com/@PsychologicalHealthCenter', 'category': 'Mental Resilience & Leadership'},
    {'name': 'Huberman Lab', 'focus': 'Stanford neuroscientist — stress inoculation protocols, sleep optimization, focus tools applicable to high-stress survival scenarios (5M+)', 'url': 'https://www.youtube.com/@hubermanlab', 'category': 'Mental Resilience & Leadership'},
    {'name': 'The Tim Kennedy Project', 'focus': 'Army Ranger / UFC fighter — physical and mental preparedness, defense mindset, training under duress', 'url': 'https://www.youtube.com/@TimKennedyMMA', 'category': 'Mental Resilience & Leadership'},
]

# Category list with counts for UI grouping
CHANNEL_CATEGORIES = sorted(set(c['category'] for c in CHANNEL_CATALOG))
