"""Static checklist template data extracted from app.py."""

CHECKLIST_TEMPLATES = {
    '72hour': {
        'name': '72-Hour Emergency Kit',
        'items': [
            {'text': 'Water — 1 gallon per person per day (3-day supply)', 'checked': False, 'cat': 'water'},
            {'text': 'Water purification tablets or filter', 'checked': False, 'cat': 'water'},
            {'text': 'Collapsible water container', 'checked': False, 'cat': 'water'},
            {'text': 'Non-perishable food (3-day supply)', 'checked': False, 'cat': 'food'},
            {'text': 'Manual can opener', 'checked': False, 'cat': 'food'},
            {'text': 'Eating utensils, plates, cups', 'checked': False, 'cat': 'food'},
            {'text': 'First aid kit (comprehensive)', 'checked': False, 'cat': 'medical'},
            {'text': 'Prescription medications (7-day supply)', 'checked': False, 'cat': 'medical'},
            {'text': 'Flashlight + extra batteries', 'checked': False, 'cat': 'gear'},
            {'text': 'Battery-powered or hand-crank radio (NOAA)', 'checked': False, 'cat': 'comms'},
            {'text': 'Cell phone charger (solar/hand-crank)', 'checked': False, 'cat': 'comms'},
            {'text': 'Whistle (signal for help)', 'checked': False, 'cat': 'gear'},
            {'text': 'Dust masks / N95 respirators', 'checked': False, 'cat': 'safety'},
            {'text': 'Plastic sheeting and duct tape (shelter-in-place)', 'checked': False, 'cat': 'shelter'},
            {'text': 'Wrench / pliers (turn off utilities)', 'checked': False, 'cat': 'tools'},
            {'text': 'Local maps (paper copies)', 'checked': False, 'cat': 'nav'},
            {'text': 'Cash in small denominations', 'checked': False, 'cat': 'docs'},
            {'text': 'Important documents (copies in waterproof bag)', 'checked': False, 'cat': 'docs'},
            {'text': 'Change of clothes per person', 'checked': False, 'cat': 'clothing'},
            {'text': 'Sturdy shoes per person', 'checked': False, 'cat': 'clothing'},
            {'text': 'Sleeping bag or warm blanket per person', 'checked': False, 'cat': 'shelter'},
            {'text': 'Rain poncho', 'checked': False, 'cat': 'clothing'},
            {'text': 'Fire extinguisher (small, portable)', 'checked': False, 'cat': 'safety'},
            {'text': 'Matches/lighter in waterproof container', 'checked': False, 'cat': 'fire'},
            {'text': 'Feminine supplies / personal hygiene items', 'checked': False, 'cat': 'hygiene'},
            {'text': 'Garbage bags and plastic ties', 'checked': False, 'cat': 'sanitation'},
            {'text': 'Paper towels, moist towelettes', 'checked': False, 'cat': 'hygiene'},
            {'text': 'Infant formula / diapers (if needed)', 'checked': False, 'cat': 'special'},
            {'text': 'Pet food and supplies (if needed)', 'checked': False, 'cat': 'special'},
            {'text': 'Books, games, puzzles (morale)', 'checked': False, 'cat': 'morale'},
        ],
    },
    'bugout': {
        'name': 'Bug-Out Bag (Go Bag)',
        'items': [
            {'text': 'Backpack (50-70L, sturdy, waterproof)', 'checked': False, 'cat': 'gear'},
            {'text': 'Water bottle + filter (Sawyer/LifeStraw)', 'checked': False, 'cat': 'water'},
            {'text': 'Water purification tablets (backup)', 'checked': False, 'cat': 'water'},
            {'text': 'Food: MREs or freeze-dried meals (3 days)', 'checked': False, 'cat': 'food'},
            {'text': 'Energy bars / trail mix', 'checked': False, 'cat': 'food'},
            {'text': 'Compact stove + fuel canister', 'checked': False, 'cat': 'food'},
            {'text': 'Metal cup / pot for boiling', 'checked': False, 'cat': 'food'},
            {'text': 'Fixed-blade knife (full tang)', 'checked': False, 'cat': 'tools'},
            {'text': 'Multi-tool (Leatherman/Gerber)', 'checked': False, 'cat': 'tools'},
            {'text': 'Ferro rod + waterproof matches', 'checked': False, 'cat': 'fire'},
            {'text': 'Tinder (cotton balls w/ vaseline)', 'checked': False, 'cat': 'fire'},
            {'text': 'Headlamp + extra batteries', 'checked': False, 'cat': 'gear'},
            {'text': 'Tarp / emergency bivvy', 'checked': False, 'cat': 'shelter'},
            {'text': 'Paracord (100 ft minimum)', 'checked': False, 'cat': 'gear'},
            {'text': 'Compass + topographic map', 'checked': False, 'cat': 'nav'},
            {'text': 'First aid kit (IFAK level)', 'checked': False, 'cat': 'medical'},
            {'text': 'Tourniquet (CAT or SOFTT-W)', 'checked': False, 'cat': 'medical'},
            {'text': 'Prescription meds (7-day supply)', 'checked': False, 'cat': 'medical'},
            {'text': 'Hand-crank / solar radio', 'checked': False, 'cat': 'comms'},
            {'text': 'FRS/GMRS radio (charged)', 'checked': False, 'cat': 'comms'},
            {'text': 'Cash + coins', 'checked': False, 'cat': 'docs'},
            {'text': 'ID / passport copies (laminated)', 'checked': False, 'cat': 'docs'},
            {'text': 'USB drive with scanned documents', 'checked': False, 'cat': 'docs'},
            {'text': 'Change of clothes (layerable)', 'checked': False, 'cat': 'clothing'},
            {'text': 'Rain gear', 'checked': False, 'cat': 'clothing'},
            {'text': 'Work gloves', 'checked': False, 'cat': 'clothing'},
            {'text': 'Bandana / shemagh', 'checked': False, 'cat': 'clothing'},
            {'text': 'Duct tape (small roll)', 'checked': False, 'cat': 'gear'},
            {'text': 'Zip ties (assorted)', 'checked': False, 'cat': 'gear'},
            {'text': 'Notepad + pencil', 'checked': False, 'cat': 'gear'},
        ],
    },
    'medical': {
        'name': 'Medical / First Aid Kit',
        'items': [
            {'text': 'Adhesive bandages (assorted sizes)', 'checked': False, 'cat': 'wound'},
            {'text': 'Sterile gauze pads (4x4)', 'checked': False, 'cat': 'wound'},
            {'text': 'Roller bandage / gauze rolls', 'checked': False, 'cat': 'wound'},
            {'text': 'Medical tape', 'checked': False, 'cat': 'wound'},
            {'text': 'Butterfly closures / steri-strips', 'checked': False, 'cat': 'wound'},
            {'text': 'Tourniquet (CAT gen 7)', 'checked': False, 'cat': 'trauma'},
            {'text': 'Hemostatic gauze (QuikClot/Celox)', 'checked': False, 'cat': 'trauma'},
            {'text': 'Israeli bandage (pressure dressing)', 'checked': False, 'cat': 'trauma'},
            {'text': 'Chest seal (vented, 2-pack)', 'checked': False, 'cat': 'trauma'},
            {'text': 'NPA airway (28Fr with lube)', 'checked': False, 'cat': 'trauma'},
            {'text': 'SAM splint', 'checked': False, 'cat': 'ortho'},
            {'text': 'ACE wrap / elastic bandage', 'checked': False, 'cat': 'ortho'},
            {'text': 'Triangle bandage / sling', 'checked': False, 'cat': 'ortho'},
            {'text': 'Nitrile gloves (multiple pairs)', 'checked': False, 'cat': 'ppe'},
            {'text': 'CPR pocket mask', 'checked': False, 'cat': 'ppe'},
            {'text': 'Trauma shears', 'checked': False, 'cat': 'tools'},
            {'text': 'Tweezers (fine point)', 'checked': False, 'cat': 'tools'},
            {'text': 'Thermometer', 'checked': False, 'cat': 'tools'},
            {'text': 'Ibuprofen / acetaminophen', 'checked': False, 'cat': 'meds'},
            {'text': 'Antihistamine (Benadryl)', 'checked': False, 'cat': 'meds'},
            {'text': 'Anti-diarrheal (Imodium)', 'checked': False, 'cat': 'meds'},
            {'text': 'Electrolyte packets (ORS)', 'checked': False, 'cat': 'meds'},
            {'text': 'Antibiotic ointment (Neosporin)', 'checked': False, 'cat': 'meds'},
            {'text': 'Hydrocortisone cream', 'checked': False, 'cat': 'meds'},
            {'text': 'Eye wash solution', 'checked': False, 'cat': 'meds'},
            {'text': 'Burn gel packets', 'checked': False, 'cat': 'meds'},
            {'text': 'Prescription medications log', 'checked': False, 'cat': 'docs'},
            {'text': 'Emergency medical info cards', 'checked': False, 'cat': 'docs'},
            {'text': 'First aid reference guide', 'checked': False, 'cat': 'docs'},
        ],
    },
    'comms': {
        'name': 'Communications Kit',
        'items': [
            {'text': 'NOAA weather radio (battery + crank)', 'checked': False, 'cat': 'receive'},
            {'text': 'FRS/GMRS handheld radio (pair)', 'checked': False, 'cat': 'twoway'},
            {'text': 'Extra batteries for all radios', 'checked': False, 'cat': 'power'},
            {'text': 'Solar charger panel (foldable)', 'checked': False, 'cat': 'power'},
            {'text': 'Power bank (20,000+ mAh)', 'checked': False, 'cat': 'power'},
            {'text': 'USB cables (multi-type)', 'checked': False, 'cat': 'power'},
            {'text': 'HAM radio (Baofeng UV-5R or better)', 'checked': False, 'cat': 'twoway'},
            {'text': 'HAM radio license study guide', 'checked': False, 'cat': 'docs'},
            {'text': 'Frequency list (laminated card)', 'checked': False, 'cat': 'docs'},
            {'text': 'CB radio (mobile or handheld)', 'checked': False, 'cat': 'twoway'},
            {'text': 'Signal mirror', 'checked': False, 'cat': 'visual'},
            {'text': 'Whistle (pealess, storm-proof)', 'checked': False, 'cat': 'visual'},
            {'text': 'Glow sticks / chem lights', 'checked': False, 'cat': 'visual'},
            {'text': 'Pen flares or road flares', 'checked': False, 'cat': 'visual'},
            {'text': 'Written comms plan (rally points, contacts)', 'checked': False, 'cat': 'docs'},
            {'text': 'Out-of-area emergency contact designated', 'checked': False, 'cat': 'docs'},
            {'text': 'Family meeting point established', 'checked': False, 'cat': 'docs'},
            {'text': 'Paper maps of local area + routes', 'checked': False, 'cat': 'nav'},
            {'text': 'Shortwave radio (for international news)', 'checked': False, 'cat': 'receive'},
            {'text': 'Faraday bag (EMP protection for electronics)', 'checked': False, 'cat': 'protect'},
        ],
    },
    'vehicle': {
        'name': 'Vehicle Emergency Kit',
        'items': [
            {'text': 'Jumper cables / jump starter pack', 'checked': False, 'cat': 'auto'},
            {'text': 'Tire repair kit + inflator', 'checked': False, 'cat': 'auto'},
            {'text': 'Spare tire (confirmed inflated)', 'checked': False, 'cat': 'auto'},
            {'text': 'Lug wrench + jack', 'checked': False, 'cat': 'auto'},
            {'text': 'Tow strap / recovery strap', 'checked': False, 'cat': 'auto'},
            {'text': 'Quart of oil + coolant', 'checked': False, 'cat': 'auto'},
            {'text': 'Fuses (assorted, matching vehicle)', 'checked': False, 'cat': 'auto'},
            {'text': 'Flashlight + spare batteries', 'checked': False, 'cat': 'gear'},
            {'text': 'Road flares / reflective triangles', 'checked': False, 'cat': 'safety'},
            {'text': 'Hi-vis vest', 'checked': False, 'cat': 'safety'},
            {'text': 'Fire extinguisher (small, mounted)', 'checked': False, 'cat': 'safety'},
            {'text': 'Basic tool kit (wrenches, screwdrivers, pliers)', 'checked': False, 'cat': 'tools'},
            {'text': 'Duct tape + zip ties + wire', 'checked': False, 'cat': 'tools'},
            {'text': 'Water (1 gallon minimum)', 'checked': False, 'cat': 'survival'},
            {'text': 'Non-perishable snacks', 'checked': False, 'cat': 'survival'},
            {'text': 'Emergency blanket / sleeping bag', 'checked': False, 'cat': 'survival'},
            {'text': 'Rain poncho', 'checked': False, 'cat': 'survival'},
            {'text': 'First aid kit', 'checked': False, 'cat': 'medical'},
            {'text': 'Paper maps / atlas', 'checked': False, 'cat': 'nav'},
            {'text': 'Pen + paper', 'checked': False, 'cat': 'gear'},
            {'text': 'Cash (small bills)', 'checked': False, 'cat': 'docs'},
            {'text': 'Phone charger (12V adapter)', 'checked': False, 'cat': 'power'},
            {'text': 'Seatbelt cutter + window breaker', 'checked': False, 'cat': 'safety'},
            {'text': 'Siphon pump', 'checked': False, 'cat': 'tools'},
        ],
    },
    'home': {
        'name': 'Home Emergency Supplies',
        'items': [
            {'text': 'Water storage — 1 gal/person/day for 14 days', 'checked': False, 'cat': 'water'},
            {'text': 'Water purification (filter, tablets, bleach)', 'checked': False, 'cat': 'water'},
            {'text': 'WaterBOB or bathtub bladder', 'checked': False, 'cat': 'water'},
            {'text': 'Food storage — 14-day supply per person', 'checked': False, 'cat': 'food'},
            {'text': 'Manual can opener (2+)', 'checked': False, 'cat': 'food'},
            {'text': 'Camp stove + fuel (outdoor use only)', 'checked': False, 'cat': 'food'},
            {'text': 'Cooler + ice plan for fridge items', 'checked': False, 'cat': 'food'},
            {'text': 'Generator + fuel (stored safely)', 'checked': False, 'cat': 'power'},
            {'text': 'Extension cords (heavy duty)', 'checked': False, 'cat': 'power'},
            {'text': 'Flashlights + lanterns (LED)', 'checked': False, 'cat': 'power'},
            {'text': 'Batteries (D, AA, AAA — bulk)', 'checked': False, 'cat': 'power'},
            {'text': 'Solar panel charger', 'checked': False, 'cat': 'power'},
            {'text': 'Propane heater (indoor-safe Mr Buddy)', 'checked': False, 'cat': 'heat'},
            {'text': 'Extra propane tanks', 'checked': False, 'cat': 'heat'},
            {'text': 'Warm blankets / sleeping bags', 'checked': False, 'cat': 'heat'},
            {'text': 'Plastic sheeting + duct tape (windows)', 'checked': False, 'cat': 'shelter'},
            {'text': 'Plywood for window boarding', 'checked': False, 'cat': 'shelter'},
            {'text': 'Sandbags (if flood zone)', 'checked': False, 'cat': 'shelter'},
            {'text': 'Comprehensive first aid kit', 'checked': False, 'cat': 'medical'},
            {'text': 'Prescription meds (30-day supply)', 'checked': False, 'cat': 'medical'},
            {'text': 'Bucket toilet + bags + kitty litter', 'checked': False, 'cat': 'sanitation'},
            {'text': 'Trash bags (heavy duty, lots)', 'checked': False, 'cat': 'sanitation'},
            {'text': 'Bleach (unscented, for sanitation)', 'checked': False, 'cat': 'sanitation'},
            {'text': 'Hand soap, sanitizer, disinfectant', 'checked': False, 'cat': 'hygiene'},
            {'text': 'Toilet paper (extra supply)', 'checked': False, 'cat': 'hygiene'},
            {'text': 'NOAA weather radio', 'checked': False, 'cat': 'comms'},
            {'text': 'Fire extinguishers (kitchen + garage)', 'checked': False, 'cat': 'safety'},
            {'text': 'Smoke + CO detectors (fresh batteries)', 'checked': False, 'cat': 'safety'},
            {'text': 'Important docs in fireproof safe', 'checked': False, 'cat': 'docs'},
            {'text': 'Cash on hand ($500+ in small bills)', 'checked': False, 'cat': 'docs'},
            {'text': 'Utility shut-off tools + knowledge', 'checked': False, 'cat': 'tools'},
            {'text': 'Axe / hatchet / pry bar', 'checked': False, 'cat': 'tools'},
        ],
    },
    'earthquake': {
        'name': 'Scenario: Earthquake',
        'items': [
            {'text': 'Check for injuries — self, then others', 'checked': False, 'cat': 'immediate'},
            {'text': 'Move to safe area away from damaged structures', 'checked': False, 'cat': 'immediate'},
            {'text': 'Check for gas leaks (smell, hissing) — shut off if suspected', 'checked': False, 'cat': 'immediate'},
            {'text': 'Check water supply — fill tubs/containers before pressure drops', 'checked': False, 'cat': 'water'},
            {'text': 'Check structural damage — do NOT enter if walls cracked/leaning', 'checked': False, 'cat': 'shelter'},
            {'text': 'Turn on NOAA weather radio for aftershock warnings', 'checked': False, 'cat': 'comms'},
            {'text': 'Wear sturdy shoes — broken glass and debris everywhere', 'checked': False, 'cat': 'safety'},
            {'text': 'Check on neighbors, especially elderly/disabled', 'checked': False, 'cat': 'community'},
            {'text': 'Photograph damage for insurance before cleanup', 'checked': False, 'cat': 'docs'},
            {'text': 'Prepare for aftershocks — stay away from chimneys and tall furniture', 'checked': False, 'cat': 'safety'},
            {'text': 'Set up alternative shelter if home is unsafe (tent, vehicle, tarp)', 'checked': False, 'cat': 'shelter'},
            {'text': 'Conserve phone battery — text instead of call', 'checked': False, 'cat': 'comms'},
        ],
    },
    'hurricane': {
        'name': 'Scenario: Hurricane/Major Storm',
        'items': [
            {'text': 'Board windows with plywood or close hurricane shutters', 'checked': False, 'cat': 'shelter'},
            {'text': 'Fill bathtub(s) with water for flushing/cleaning', 'checked': False, 'cat': 'water'},
            {'text': 'Charge all devices, battery packs, and radios', 'checked': False, 'cat': 'power'},
            {'text': 'Move vehicles to highest ground available', 'checked': False, 'cat': 'vehicle'},
            {'text': 'Secure or bring inside all outdoor furniture/objects', 'checked': False, 'cat': 'shelter'},
            {'text': 'Fill vehicle fuel tanks completely', 'checked': False, 'cat': 'fuel'},
            {'text': 'Withdraw cash ($500+ small bills)', 'checked': False, 'cat': 'docs'},
            {'text': 'Set fridge/freezer to coldest — food lasts longer in power outage', 'checked': False, 'cat': 'food'},
            {'text': 'Know your evacuation zone and route', 'checked': False, 'cat': 'evac'},
            {'text': 'Stage go-bags at door if evacuation may be needed', 'checked': False, 'cat': 'evac'},
            {'text': 'Move to interior room during storm (no windows)', 'checked': False, 'cat': 'safety'},
            {'text': 'After storm: avoid downed power lines and standing water', 'checked': False, 'cat': 'safety'},
        ],
    },
    'pandemic': {
        'name': 'Scenario: Pandemic/Quarantine',
        'items': [
            {'text': 'Stock 30+ days of food and water per person', 'checked': False, 'cat': 'food'},
            {'text': 'Stock 90-day supply of prescription medications', 'checked': False, 'cat': 'medical'},
            {'text': 'N95/KN95 masks — minimum 50 per person', 'checked': False, 'cat': 'medical'},
            {'text': 'Nitrile gloves, hand sanitizer, disinfectant', 'checked': False, 'cat': 'hygiene'},
            {'text': 'Thermometer and pulse oximeter', 'checked': False, 'cat': 'medical'},
            {'text': 'Establish quarantine room/area if household member gets sick', 'checked': False, 'cat': 'medical'},
            {'text': 'Set up contactless delivery/pickup protocols', 'checked': False, 'cat': 'supply'},
            {'text': 'Home school/education materials for children', 'checked': False, 'cat': 'morale'},
            {'text': 'Entertainment/morale supplies for extended isolation', 'checked': False, 'cat': 'morale'},
            {'text': 'Establish check-in schedule with family/neighbors', 'checked': False, 'cat': 'comms'},
            {'text': 'Disinfect all incoming packages/deliveries', 'checked': False, 'cat': 'hygiene'},
            {'text': 'Backup internet/comms plan if ISP fails', 'checked': False, 'cat': 'comms'},
        ],
    },
    'wildfire': {
        'name': 'Scenario: Wildfire Evacuation',
        'items': [
            {'text': 'Monitor fire maps and evacuation orders continuously', 'checked': False, 'cat': 'intel'},
            {'text': 'Load go-bags in vehicle NOW — do not wait for mandatory evac', 'checked': False, 'cat': 'evac'},
            {'text': 'Important documents, photos, irreplaceable items in car first', 'checked': False, 'cat': 'docs'},
            {'text': 'Close all windows, doors, and vents to slow ember entry', 'checked': False, 'cat': 'shelter'},
            {'text': 'Connect garden hoses, fill pools/tubs/trash cans with water', 'checked': False, 'cat': 'defense'},
            {'text': 'Move flammable furniture away from windows', 'checked': False, 'cat': 'shelter'},
            {'text': 'Remove flammable items from around house (30ft clearance)', 'checked': False, 'cat': 'defense'},
            {'text': 'N95 masks for smoke — limit outdoor exposure', 'checked': False, 'cat': 'medical'},
            {'text': 'Know 2+ evacuation routes — primary route may be blocked', 'checked': False, 'cat': 'evac'},
            {'text': 'Livestock/pets loaded and ready', 'checked': False, 'cat': 'evac'},
            {'text': 'Leave lights on and a note on door with destination info', 'checked': False, 'cat': 'comms'},
            {'text': 'DO NOT return until authorities give all-clear', 'checked': False, 'cat': 'safety'},
        ],
    },
    'civil_unrest': {
        'name': 'Scenario: Civil Unrest',
        'items': [
            {'text': 'Stay home — avoid protest/riot areas entirely', 'checked': False, 'cat': 'safety'},
            {'text': 'Lock and secure all entry points', 'checked': False, 'cat': 'security'},
            {'text': 'Close blinds/curtains — do not attract attention', 'checked': False, 'cat': 'security'},
            {'text': 'Park vehicles in garage or away from street', 'checked': False, 'cat': 'security'},
            {'text': 'Verify food/water supply for 2+ weeks sheltering in place', 'checked': False, 'cat': 'supply'},
            {'text': 'Keep all devices charged — power disruptions possible', 'checked': False, 'cat': 'power'},
            {'text': 'Monitor multiple news/radio sources for situational awareness', 'checked': False, 'cat': 'intel'},
            {'text': 'Establish neighborhood watch communication with trusted neighbors', 'checked': False, 'cat': 'comms'},
            {'text': 'Have fire extinguishers accessible (arson risk)', 'checked': False, 'cat': 'safety'},
            {'text': 'Know alternate routes to hospital/pharmacy if primary roads blocked', 'checked': False, 'cat': 'medical'},
            {'text': 'Cash on hand — ATMs and card systems may go down', 'checked': False, 'cat': 'docs'},
            {'text': 'Gray man principles — do not display wealth, supplies, or opinions', 'checked': False, 'cat': 'opsec'},
        ],
    },
    'winter_storm': {
        'name': 'Scenario: Winter Storm / Ice Storm',
        'items': [
            {'text': 'Stock firewood / fuel for 7+ days of heating', 'checked': False, 'cat': 'heating'},
            {'text': 'Insulate windows with plastic film or heavy curtains', 'checked': False, 'cat': 'shelter'},
            {'text': 'Pipe insulation or heat tape on exposed plumbing', 'checked': False, 'cat': 'shelter'},
            {'text': 'Water stored in case pipes freeze (1 gal/person/day x 7 days)', 'checked': False, 'cat': 'water'},
            {'text': 'Non-perishable food (no cooking required) for 7 days', 'checked': False, 'cat': 'food'},
            {'text': 'Extra blankets, sleeping bags, thermal underwear', 'checked': False, 'cat': 'warmth'},
            {'text': 'Battery/crank-powered radio for weather alerts', 'checked': False, 'cat': 'comms'},
            {'text': 'Flashlights, lanterns, extra batteries', 'checked': False, 'cat': 'light'},
            {'text': 'Generator fueled + extension cords ready', 'checked': False, 'cat': 'power'},
            {'text': 'Carbon monoxide detector with fresh batteries', 'checked': False, 'cat': 'safety'},
            {'text': 'Snow shovel, ice melt, sand/kitty litter for traction', 'checked': False, 'cat': 'tools'},
            {'text': 'Vehicle: full tank, winter kit (blanket, shovel, chains, flares)', 'checked': False, 'cat': 'vehicle'},
            {'text': 'Medications: 14-day supply on hand', 'checked': False, 'cat': 'medical'},
            {'text': 'Let faucets drip to prevent pipe freezing', 'checked': False, 'cat': 'shelter'},
            {'text': 'Know location of water shut-off valve', 'checked': False, 'cat': 'shelter'},
        ],
    },
    'grid_down': {
        'name': 'Scenario: Extended Power Grid Failure',
        'items': [
            {'text': 'Fill all water containers immediately (water pressure will drop)', 'checked': False, 'cat': 'water'},
            {'text': 'Inventory food: eat perishables first, then frozen, then shelf-stable', 'checked': False, 'cat': 'food'},
            {'text': 'Unplug sensitive electronics to prevent surge damage on restoration', 'checked': False, 'cat': 'power'},
            {'text': 'Generator: test, fuel, extension cords, run OUTSIDE only', 'checked': False, 'cat': 'power'},
            {'text': 'Solar panels and battery banks charged and accessible', 'checked': False, 'cat': 'power'},
            {'text': 'Cash on hand ($500+ in small bills) — electronic payments are down', 'checked': False, 'cat': 'finance'},
            {'text': 'Fill vehicle gas tanks (pumps need electricity)', 'checked': False, 'cat': 'fuel'},
            {'text': 'Battery/crank radio for information', 'checked': False, 'cat': 'comms'},
            {'text': 'HAM/FRS/GMRS radio charged for local communication', 'checked': False, 'cat': 'comms'},
            {'text': 'Establish neighborhood watch / check on elderly neighbors', 'checked': False, 'cat': 'security'},
            {'text': 'Security: lock doors, close curtains, low profile after dark', 'checked': False, 'cat': 'security'},
            {'text': 'Medical: inventory all medications, calculate days of supply', 'checked': False, 'cat': 'medical'},
            {'text': 'Sanitation plan: bucket toilet with bags + kitty litter if water fails', 'checked': False, 'cat': 'sanitation'},
            {'text': 'Cooking: camp stove, grill, or fire pit with fuel supply', 'checked': False, 'cat': 'food'},
            {'text': 'Entertainment: books, cards, board games (morale matters)', 'checked': False, 'cat': 'morale'},
        ],
    },
    'shelter_in_place': {
        'name': 'Scenario: Shelter-in-Place (Chemical/Nuclear)',
        'items': [
            {'text': 'Get INSIDE immediately — sealed building is best protection', 'checked': False, 'cat': 'shelter'},
            {'text': 'Close and lock all windows and doors', 'checked': False, 'cat': 'shelter'},
            {'text': 'Turn OFF HVAC / air conditioning / fans', 'checked': False, 'cat': 'shelter'},
            {'text': 'Seal door gaps with wet towels', 'checked': False, 'cat': 'shelter'},
            {'text': 'Tape plastic sheeting over windows and vents', 'checked': False, 'cat': 'shelter'},
            {'text': 'Move to interior room above ground level', 'checked': False, 'cat': 'shelter'},
            {'text': 'Monitor NOAA radio / emergency broadcasts for all-clear', 'checked': False, 'cat': 'comms'},
            {'text': 'Water: fill containers from tap BEFORE contamination reaches supply', 'checked': False, 'cat': 'water'},
            {'text': 'Potassium iodide (KI) tablets if nuclear — take per instructions', 'checked': False, 'cat': 'medical'},
            {'text': 'DO NOT go outside to check conditions', 'checked': False, 'cat': 'safety'},
            {'text': 'Cover nose and mouth with wet cloth if air quality degrades', 'checked': False, 'cat': 'safety'},
            {'text': 'Account for all household members — do not separate', 'checked': False, 'cat': 'family'},
            {'text': 'If contamination suspected on skin/clothes: remove outer clothing, shower', 'checked': False, 'cat': 'decon'},
            {'text': 'Remain sheltered minimum 24 hours (nuclear) or until all-clear (chemical)', 'checked': False, 'cat': 'shelter'},
        ],
    },
    'infant_emergency': {
        'name': 'Infant / Baby Emergency Kit',
        'items': [
            {'text': 'Formula or breastmilk storage (3-day supply minimum)', 'checked': False, 'cat': 'food'},
            {'text': 'Bottles, nipples, bottle brush, dish soap', 'checked': False, 'cat': 'feeding'},
            {'text': 'Diapers (minimum 50) + wipes (2 packs)', 'checked': False, 'cat': 'hygiene'},
            {'text': 'Diaper rash cream', 'checked': False, 'cat': 'medical'},
            {'text': 'Baby Tylenol (infant acetaminophen) + dosing syringe', 'checked': False, 'cat': 'medical'},
            {'text': 'Pedialyte or ORS packets (dehydration prevention)', 'checked': False, 'cat': 'medical'},
            {'text': 'Warm clothing layers + hat + socks (season appropriate)', 'checked': False, 'cat': 'clothing'},
            {'text': 'Blankets (2 receiving, 1 heavier)', 'checked': False, 'cat': 'warmth'},
            {'text': 'Pacifiers (if used) — 2 minimum', 'checked': False, 'cat': 'comfort'},
            {'text': 'Baby carrier (hands-free, for evacuation)', 'checked': False, 'cat': 'gear'},
            {'text': 'Clean water for mixing formula (if not breastfeeding)', 'checked': False, 'cat': 'water'},
            {'text': 'Small first aid kit: thermometer, nasal aspirator, nail clippers', 'checked': False, 'cat': 'medical'},
            {'text': 'Birth certificate + insurance card copies', 'checked': False, 'cat': 'docs'},
            {'text': 'Comfort item (stuffed animal, favorite toy)', 'checked': False, 'cat': 'comfort'},
            {'text': 'Portable crib or pack-n-play (if evacuating)', 'checked': False, 'cat': 'gear'},
        ],
    },
}
